### ISSUE TITLE
On Linux also need to supply -Xlinker='-lrt' as argument to swift run

### ISSUE THREAD

**Issue by Reshahar** [googleprojectzero/fuzzilli#10]
On Linux  also need to supply ` -Xlinker='-lrt' `as argument to `swift run`

**Comment by shogunlab** [comment]
For reference, on Linux this is the full run command I used to start the fuzzer successfully using JSC as a target:
`swift run -Xlinker='-lrt' -c release FuzzilliCli --profile=jsc /path/to/fuzzbuild/jsc`

**Comment by saelo** [comment]
Thanks! I updated the README: https://github.com/googleprojectzero/fuzzilli/commit/5a3aacac7dba31f18cab4553766824d3996e6c1a
