### ISSUE TITLE
Build testing infrastructure with access to a working JavaScript engine

### ISSUE THREAD

**Issue by saelo** [googleprojectzero/fuzzilli#100]
it would be nice to have a testing infrastructure (similar to or included in Tests/) that has access to a JavaScript engine to execute scripts on. Preferably, any of the supported JavaScript engines could be used for this and ideally this would even work on the CI. Some of the things that could then be tested include:
- The lifter, and its different modes
- Runtime type collection
- REPRL
- Coverage collection
- Minimization
- Some other stuff from `runStartupTests`

**Comment by WilliamParks** [comment]
This would also be useful for the tests in the Compiler, in detecting issues such as the variable issue here: https://github.com/googleprojectzero/fuzzilli/pull/169#pullrequestreview-539790985
