### ISSUE TITLE
Script execution failed: Did not receive HELO message from child

### ISSUE THREAD

**Issue by Denimoll** [googleprojectzero/fuzzilli#105]
Hello, fuzzillian genius.
I have one problem and a few Q.
I do this (ubuntu 20.04):
1. `git clone fuzzilli `(/opt/fuzzilli);
2. in Targets/JavaScriptCore: `git clone webkit` and `git apply Patches/webkit.patch`;
3. in webkit dir `../fuzzbuild.sh`
4. in /opt/fuzzilli `swift build -c release` and `swift run -c release FuzzilliCli --profile=jsc Targets/JavaScriptCore/webkit/FuzzBuild/Debug/bin/jsc`

After this I have this:
```
[Cli] No filesystem storage configured, found crashes will be discarded!
[REPRL] Script execution failed: Did not receive HELO message from child. Retrying in 1 second...
[REPRL] Script execution failed again: Did not receive HELO message from child. Giving up
[LibCoverage] Coverage bitmap size could not be determined, is the engine instrumentation working properly?
```

What's wrong? And what this command do? How can i run fuzzilli on real code? I want to check some JS code on my big project (PS: I have some sripts on another language too, but i think it isnt problem).

**Comment by saelo** [comment]
Hi, did the patch apply without errors? Also, did you use the version specified in.the `REVISION` file for JSC? You can also follow the steps from the Dockerfile to get a working JSC build: https://github.com/googleprojectzero/fuzzilli/blob/master/Cloud/Docker/JSCBuilder/Dockerfile hope that helps!
Also keep in mind that Fuzzilli is for fuzzing JavaScript engines, not JavaScript code.

**Comment by Denimoll** [comment]
Oh, I didn't understand at first. I just looking for fuzzers for fuzzing my code.
If I ever need it, I'll go back to fuzzilli 100%. Thank you for reply and this fuzzer.
