### ISSUE TITLE
CodeGenerators that spread should be more careful

### ISSUE THREAD

**Issue by saelo** [googleprojectzero/fuzzilli#108]
There are currently three different FuzzIL operations (and corresponding CodeGenerators) that do spreading:
- CreateObjectWithSpread (`v1 = {...v0};`)
- CreateArrayWithSpread (`v1 = [...v0];`)
- CallFunctionWithSpread (`v2 = v1(...v0);`)

in the first case, the spreading will enumerate the properties of the spread value, which is basically possible on every type. However, in the second and third case, it will perform an iteration (and therefore look up the `Symbol.iterator` property), which is only valid on things like Arrays and Strings. As such, the CodeGenerators for them should ensure that spreading is safely possible, for example through a helper function `isIterable` that statically determines whether a variable holds an iterable object.

**Comment by carl-smith** [comment]
There is a similar phenomenon that happens with for-of loops.
E.g. `for (x of Object)` will fail as `Object` is not iterable. These generators could also benefit from such a helper function.
