### ISSUE TITLE
Consistent int type for exec_time in reprl_result suggested.

### ISSUE THREAD

**Issue by dwfault** [googleprojectzero/fuzzilli#11]
Hello saelo! Thanks for sharing fuzzilli with us!

This is a bug report that could trigger on some CPUs, and on those CPUs, fuzzilli always crash as follows:

$/home/ubuntu/Desktop/fuzzilli/.build/x86_64-unknown-linux/debug/FuzzilliCli --profile=jsc ../webkit/FuzzBuild/Debug/bin/jsc

#0  0x00007ffff7bc30e1 in $Ss18_fatalErrorMessage__4file4line5flagss5NeverOs12StaticStringV_A2HSus6UInt32VtFTf4nnddn_n () from /home/ubuntu/Desktop/swift4/usr/lib/swift/linux/libswiftCore.so
#1  0x00007ffff79ea11a in $SSZss17FixedWidthIntegerRzrlEyxqd__cSzRd(long, float __restrict,  const) ()
   from /home/ubuntu/Desktop/swift4/usr/lib/swift/linux/libswiftCore.so
#2  0x00005555555aef69 in $S8Fuzzilli5REPRLC3run_11withTimeoutAA9ExecutionVSS_s6UInt32VtF (script=..., 
    timeout=..., self=...) at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Execution/REPRL.swift:151
#3  0x00005555555af8b6 in $S8Fuzzilli5REPRLCAA12ScriptRunnerA2aDP3run_11withTimeoutAA9ExecutionVSS_s6UInt32VtFTW ()
#4  0x00005555555f2f48 in $S8Fuzzilli6FuzzerC7execute_11withTimeoutAA9ExecutionVAA7ProgramC_s6UInt32VSgtF
    (program=..., timeout=..., self=...)
    at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Fuzzer.swift:200
#5  0x0000555555627677 in $S8Fuzzilli17ReductionVerifierC4testySbAA7ProgramCF (reducedProgram=..., 
    self=...) at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Minimization/Reducer.swift:39
#6  0x0000555555627a5a in $S8Fuzzilli17ReductionVerifierC12tryReplacing13instructionAt4with2inSbSi_AA11InstructionVAA7ProgramCtF (index=..., newInstr=..., program=..., self=...)
    at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Minimization/Reducer.swift:54
#7  0x0000555555627c86 in $S8Fuzzilli17ReductionVerifierC10tryNopping13instructionAt2inSbSi_AA7ProgramCtF
    (index=..., program=..., self=...)
    at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Minimization/Reducer.swift:67
#8  0x000055555561ea9a in $S8Fuzzilli25GenericInstructionReducerV6reduce_4withAA7ProgramCAG_AA17ReductionVerifierCtF (program=..., verifier=..., self=...)
    at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Minimization/GenericInstructionReducer.swift:23
#9  0x000055555561ed69 in $S8Fuzzilli25GenericInstructionReducerVAA0D0A2aDP6reduce_4withAA7ProgramCAI_AA17ReductionVerifierCtFTW ()
#10 0x0000555555624e67 in $S8Fuzzilli9MinimizerC8minimize_11withAspectsAA7ProgramCAG_AA0fE0CtF (
    program=..., aspects=..., self=...)
    at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Minimization/Minimizer.swift:48
#11 0x0000555555589ab3 in $S8Fuzzilli10FuzzerCoreC18processInteresting33_3ACCD2E86945CBBB1D5983F9A675FC4DLL_13havingAspects10isImportedyAA7ProgramC_AA0qN0CSbtF (program=..., aspects=..., isImported=..., 
    self=...) at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Core/FuzzerCore.swift:212
#12 0x0000555555588622 in $S8Fuzzilli10FuzzerCoreC7fuzzOneyyF (self=...)
    at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Core/FuzzerCore.swift:153
#13 0x00005555555f336e in $S8Fuzzilli6FuzzerC7fuzzOne33_54ECDA97F7E6F07CDC352895C65FED23LLyyF (self=...)
    at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Fuzzer.swift:224
#14 0x00005555555f349b in $S8Fuzzilli6FuzzerC7fuzzOne33_54ECDA97F7E6F07CDC352895C65FED23LLyyFyycfU_ ()
    at /home/ubuntu/Desktop/fuzzilli/Sources/Fuzzilli/Fuzzer.swift:228
#15 0x00005555555f646c in $S8Fuzzilli6FuzzerC7fuzzOne33_54ECDA97F7E6F07CDC352895C65FED23LLyyFyycfU_TA ()
#16 0x00005555555a143d in $SIeg_IeyB_TR ()
#17 0x00007ffff7f328c7 in _dispatch_call_block_and_release ()
   from /home/ubuntu/Desktop/swift4/usr/lib/swift/linux/libdispatch.so
#18 0x00007ffff7f40efc in _dispatch_main_queue_callback_4CF ()
   from /home/ubuntu/Desktop/swift4/usr/lib/swift/linux/libdispatch.so
#19 0x00007ffff72954f8 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
   from /home/ubuntu/Desktop/swift4/usr/lib/swift/linux/libFoundation.so
#20 0x00007ffff72915a9 in __CFRunLoopRun ()
   from /home/ubuntu/Desktop/swift4/usr/lib/swift/linux/libFoundation.so
#21 0x00007ffff7290be8 in CFRunLoopRunSpecific ()
   from /home/ubuntu/Desktop/swift4/usr/lib/swift/linux/libFoundation.so
#22 0x00007ffff75447fe in $S10Foundation7RunLoopC3runyyF ()
   from /home/ubuntu/Desktop/swift4/usr/lib/swift/linux/libFoundation.so
#23 0x0000555555678356 in main () at /home/ubuntu/Desktop/fuzzilli/Sources/FuzzilliCli/main.swift:204
#24 0x00007ffff5b85830 in __libc_start_main (main=0x555555672f90 <main>, argc=0x3, argv=0x7fffffffdc18, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc08)
    at ../csu/libc-start.c:291
#25 0x0000555555575799 in _start ()

This is because Sources/libreprl/include/libreprl.h has:

struct reprl_result {
    int child_died;
    int status;
    unsigned long exec_time;  //---->
    char* output;
    size_t output_size;
};

While  Sources/Fuzzilli/Execution/Execution.swift has:

/// The result of executing a program.
public struct Execution {
    /// The script that was executed to produce this result
    public let script: String
    
    /// The PID of the process that executed the program
    public let pid: Int
    
    /// The execution outcome
    public let outcome: ExecutionOutcome
    
    /// The termination signal
    public let termsig: Int
    
    /// Program output (not stdout but FuzzIL output)
    public let output: String
    
    /// Execution time in ms
    public let execTime: Int           // ------>
}

And latter execTime is used as signed int such as:

        var maxExecutionTime = -1
        // Dispatch a non-trivial program and measure its execution time
        let complexProgram = makeComplexProgram()
        for _ in 0..<5 {
            let execution = execute(complexProgram)
            maxExecutionTime = max(maxExecutionTime, execution.execTime)  // ------>
        }

So reprl_result.exec_time could be defined as "long". It's better to define execTime as unsigned or something, but of course more code has to be changed. Thanks :)

**Comment by saelo** [comment]
I've changed `execTime` to be an unsigned int in https://github.com/googleprojectzero/fuzzilli/commit/da6f7656d5044aeb8b98ba621734aec8c9fef35a. Can you confirm that this fixes the issue as I am unable to reproduce it on my setup?

**Comment by dwfault** [comment]
Sure, test started and running : )

**Comment by dwfault** [comment]
@saelo I think this one is properly fixed. And here's what I know for the root cause of the problem:
On virtual machine enviroments some CPU clock is not reliable, and stuffs like exec_time and interval that yield from substraction  would sometimes return negative value...I run a same vm on different CPUs. And I think it is a hardware problem.

**Comment by dwfault** [comment]
Thanks very much : )

**Comment by saelo** [comment]
Ah interesting, thanks for investigating!
