### ISSUE TITLE
How to get Fuzzilli to ignore certain crash signatures?

### ISSUE THREAD

**Issue by nclman** [googleprojectzero/fuzzilli#132]
Some types of crashes are controlled ones which are generally not useful.
Does Fuzzilli have a mechanism to ignore certain types of crashes?

**Comment by saelo** [comment]
Hi! No, there is no mechanism for this and it would probably be quite fiddly to implement and somewhat dangerous to have. How can Fuzzilli be sure that a `RELEASE_ASSERT` you are triggering isn't the symptom of a bug that can also be triggered in other ways? Fuzzilli should include stderr output as comment in the repro file for each crash. With that, you should be able to just grep through the failure messages etc. and do some quick initial filtering based on that.

**Comment by nclman** [comment]
Thanks for the quick answer! Will close this...
