### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by jlamendo** [googleprojectzero/fuzzilli#14]
I've made a dockerfile for fuzzilli/v8 at https://gist.github.com/jlamendo/b013a8904032fb1600583ddc64714571

This probably doesn't belong in an issue, but I wanted to share it in the hopes that it would save someone else some time and wasn't sure where to put it so people could see it. If you'd like me to open a PR to add the dockerfile to the repo or to the readme, let me know. Happy Fuzzing!

P.S. - Thanks for the great fuzzer! Really enjoying this IL approach to fuzzing - very approachable and easy to configure.

**Comment by saelo** [comment]
Thanks! Yes I'm also using a number of docker files and scripts myself to run fuzzilli on GCE. It would be good to have a decent setup for building all supported JS engines (with the custom patches) and fuzzilli with docker, so I will just leave this issue open to track that.
Btw. there are also [docker images for swift](https://hub.docker.com/_/swift/) which are probably a bit easier to use in this case.

**Comment by saelo** [comment]
Done: https://github.com/googleprojectzero/fuzzilli/commit/5dca6712dacfeae7f7caef8d981e734a6b19e11d
