### ISSUE TITLE
Failed to communicate with child process with firefox

### ISSUE THREAD

**Issue by xcainiao** [googleprojectzero/fuzzilli#15]
when I run with gecko-dev this error happened.

**Comment by saelo** [comment]
That sounds like the Spidermonkey patches did not apply correctly. You can try uncommenting [these lines](https://github.com/googleprojectzero/fuzzilli/blob/d626580ef1637ee018e0700717e1f46ce90de09a/Sources/libreprl/libreprl.c#L104) to see output from the child processes. Also you can run the target inside the [REPRL tester](https://github.com/googleprojectzero/fuzzilli/tree/d626580ef1637ee018e0700717e1f46ce90de09a/Misc/REPRL) (`./tester /path/to/dist/bin/js --reprl`) to see if REPRL support works in the child process.

**Comment by xcainiao** [comment]
Thank you for your reply, now I solve the problem, it is because I compile gecko-dev js error.
