### ISSUE TITLE
the longer timer runing, the higher of overhead

### ISSUE THREAD

**Issue by maldiohead** [googleprojectzero/fuzzilli#177]
at start, the execution rate is 1400 sample per second with 88 threads,after 24 hours it's only 90 sample per second while with high overhead.

**Comment by saelo** [comment]
Hi! I'm merging this issue with https://github.com/googleprojectzero/fuzzilli/issues/174 
But also note that the execution rate naturally decreases significantly over time as the samples become more complex, e.g. because they trigger JIT compilation.
