### ISSUE TITLE
Seed input location

### ISSUE THREAD

**Issue by lexylee2406** [googleprojectzero/fuzzilli#181]
Hello @saelo, 

Thank you very much for making this interesting fuzzing tool open source.

I am trying to understand the source code of Fuzzilli and how it works. According to what you wrote in your Master thesis, specifically on page 30, I understand that Fuzzilli takes the following simple FuzzIL as seed input.

v0 <− LoadGlobal ”Object”
v1 <− CallFunction v0

However, I don't know where the seed is stored. I ask this question because I am thinking whether I can (manually) add more seeds, written in pure FuzzIL language, to enlarge the corpus. 

LL.

**Comment by saelo** [comment]
Hi! You can find the seed program here: https://github.com/googleprojectzero/fuzzilli/blob/4129b6735e310058506cf7550b9b4d16fe574c9c/Sources/Fuzzilli/Core/Corpus.swift#L68

You can either manually add more seed programs in FuzzIL, or checkout the [new compiler](https://github.com/googleprojectzero/fuzzilli/pull/169) to compile JavaScript to FuzzIL, then import that corpus using [one of the corpus import flags](https://github.com/googleprojectzero/fuzzilli/blob/4129b6735e310058506cf7550b9b4d16fe574c9c/Sources/FuzzilliCli/main.swift#L51) :)
