### ISSUE TITLE
QJS-Patch Error

### ISSUE THREAD

**Issue by vacanthu** [googleprojectzero/fuzzilli#182]
i tried to fllow the step to install fuzzilli for fuzzing QuickJs.
![微信图片_20210130143643](https://user-images.githubusercontent.com/39495020/106349418-a4c20900-6308-11eb-91d8-b5a27b695ba2.png)
but i get stucked in there.Could you tell me where's the problem ? thanks a lot
![微信图片_20210130143831](https://user-images.githubusercontent.com/39495020/106349447-d6d36b00-6308-11eb-8e64-64e637ff4323.png)

**Comment by saelo** [comment]
Hi! Seems the patch was slightly broken, it should work now after https://github.com/googleprojectzero/fuzzilli/commit/70be6aafaf827bf4bb4e0497749205ea66a34d27

Note that the specified QuickJS revision is fairly old (mid 2020), so you might want to rebase the patch to a newer version. If you do so, please feel free to send a PR.
