### ISSUE TITLE
Build failed 'use of unresolved identifier 'runREPRLTests''

### ISSUE THREAD

**Issue by dorattias** [googleprojectzero/fuzzilli#184]
building fuzzili of MacOS Big Sur 11.1 failed with the following output

`swift build -c release
`
```
fuzzilli/Sources/REPRLRun/main.swift:61:1: error: use of unresolved identifier 'runREPRLTests'
runREPRLTests()
```

**Comment by docfate111** [comment]
@dorattias How did you fix it? I'm running into the same issue.

**Comment by dorattias** [comment]
@docfate111
I used tag v0.9.1 instead of master. There is some
modifications there that solve the problem.
