### ISSUE TITLE
Cannot check if crashes are detected

### ISSUE THREAD

**Issue by docfate111** [googleprojectzero/fuzzilli#186]
What did I do wrong? Please help me.
```
Coverage] Initialized, 0 edges
[Fuzzer] Initialized
[Fuzzer] Cannot check if crashes are detected
[Fuzzer] Recommended timeout: at least 10ms. Current timeout: 250ms
[Fuzzer] Cannot receive FuzzIL output
[Fuzzer] Startup tests finished successfully
```
https://github.com/docfate111/mujs-fuzzilli/blob/main/main.c
I made the REPL loop from the other targets and pseudocode. 
Is there any step I missed because I double-checked and it looks fine.

**Comment by saelo** [comment]
Fuzzilli can only check for crashes if you define `crashTests` in your profile, see e.g. [here](https://github.com/googleprojectzero/fuzzilli/blob/ad2941585592c0251945f2548ffa1b62256af5c7/Sources/FuzzilliCli/Profiles/V8Profile.swift#L152). Do you have those?

**Comment by docfate111** [comment]
Thanks I missed that. However I think there is something wrong with my REPL, the fuzzer runs but I am getting
```
[Fuzzer] Cannot receive FuzzIL output
```
https://github.com/docfate111/mujs-fuzzilli/blob/main/main.c

**Comment by saelo** [comment]
Does your patch include support for the `FUZZILLI_PRINT` functionality (which should write the argument to `REPRL_DWFD `, see e.g. [here](https://github.com/googleprojectzero/fuzzilli/blob/ad2941585592c0251945f2548ffa1b62256af5c7/Targets/JavaScriptCore/Patches/webkit.patch#L208)). That's usually the problem when this warning appears.

**Comment by docfate111** [comment]
It does not. Is there supposed to be a javascript function that takes FUZZILLI_PRINT as an argument? Or do I just wait for the string to be in stdin? What do I return?

**Comment by docfate111** [comment]
https://github.com/docfate111/mujs-fuzzilli/blob/main/main.c

**Comment by saelo** [comment]
I assume this issue is no longer active, but feel free to reopen!
