### ISSUE TITLE
All generated test cases

### ISSUE THREAD

**Issue by vacanthu** [googleprojectzero/fuzzilli#192]
Can i get all the generated test cases based on the given seed corpus? if can, how can i get those. what's more, can i change the seed corpus to my own corpus to generated test cases and get them?

**Comment by saelo** [comment]
You can find the generated JavaScript programs that are added to the corpus in the output directory, but there is currently no way to dump _all_ generated programs. For that, you'd probably need to hook either [here](https://github.com/googleprojectzero/fuzzilli/blob/50589694353fad83b7763eca8c5860a119ca63ae/Sources/Fuzzilli/Fuzzer.swift#L380) or [here](https://github.com/googleprojectzero/fuzzilli/blob/50589694353fad83b7763eca8c5860a119ca63ae/Sources/Fuzzilli/Core/MutationEngine.swift#L142) (the first will also give you programs executed for minimization etc. while the latter will only give you programs generated by the mutation engine). 
You can manually add programs to the input corpus [here](https://github.com/googleprojectzero/fuzzilli/blob/50589694353fad83b7763eca8c5860a119ca63ae/Sources/Fuzzilli/Core/Corpus.swift#L66) or you can [import an existing corpus](https://github.com/googleprojectzero/fuzzilli/blob/50589694353fad83b7763eca8c5860a119ca63ae/Sources/FuzzilliCli/main.swift#L51), for example by [compiling existing JavaScript to FuzzIL](https://github.com/googleprojectzero/fuzzilli/pull/169).

Hope that helps!

**Comment by vacanthu** [comment]
thank a lot for your help, hava a good holiday.
