### ISSUE TITLE
Missing weight for code generator BinaryOperationAndReassignGenerator in CodeGeneratorWeights.swift

### ISSUE THREAD

**Issue by Lqingyu** [googleprojectzero/fuzzilli#215]
Hello,

I use docker file to fuzz v8. According to the readme operation, the following error was reported, how can I solve it?

```
fuzzilli/Cloud/Docker$ docker run -ti fuzzilli ./Fuzzilli --profile=v8 ./v8/d8
Missing weight for code generator BinaryOperationAndReassignGenerator in CodeGeneratorWeights.swift
```

**Comment by saelo** [comment]
I believe this was fixed [here](https://github.com/googleprojectzero/fuzzilli/commit/98298d18135340823f6852550c95c23ccf037532#diff-44d642e28a9b4bcd4ad421bf0c4cea47449dbb674dc35fddd14fc404a365e3e2R62) but please double check with latest HEAD.
