### ISSUE TITLE
Unknown flag --debug-code for V8 Profile

### ISSUE THREAD

**Issue by kinzhong** [googleprojectzero/fuzzilli#219]
Hello!

Just wanted to check if the flags for V8 profile are correct. I used the most recent v8 engine and built it using fuzzbuild.sh. However, I noticed that the --debug-code flag is not present in d8 but is present in [V8Profile.swift:128](https://github.com/googleprojectzero/fuzzilli/blob/main/Sources/FuzzilliCli/Profiles/V8Profile.swift#L128). 

Thank you.

**Comment by saelo** [comment]
Indeed, I guess it was removed from V8 at some point? Anyway, removed it now with https://github.com/googleprojectzero/fuzzilli/commit/b299bd5b5526de65820457b7e39dcf34080c4e0a Thanks for the report!
