### ISSUE TITLE
Question about V8 builtins

### ISSUE THREAD

**Issue by oicu0619** [googleprojectzero/fuzzilli#226]
Hi! i am currently trying to compile V8 testcases to fuzzil IR, and i have a question about V8 builtins.
There is a lot of V8 builtins(like OptimizeFunctionOnNextCall) defined in V8 runtime.h and used by V8 testcases, a lot more than additionalBuiltins defined in fuzzilli Sources/FuzzilliCli/Profiles/V8Profile.swift. What to do you think is a good way to treat these builtins?
Also, if we add v8 builtins to additionalBuiltins, it will become target of the mutation of "LoadBuiltin". I am not sure do we want that or not? 
Thanks a lot for the help!

**Comment by saelo** [comment]
Right, I think adding them to `additionalBuiltins` and wrapping them in a pseudo-function (see [here](https://github.com/googleprojectzero/fuzzilli/blob/bc057d1eb2d47878b700022e59409e974bd01597/Sources/FuzzilliCli/Profiles/V8Profile.swift#L138)) is probably the right way to go. Alternatively, you could compile them as `Eval` operations if you don't want the additional builtins to be used. See [here](https://github.com/googleprojectzero/fuzzilli/blob/bc057d1eb2d47878b700022e59409e974bd01597/Sources/FuzzilliCli/Profiles/V8Profile.swift#L123) for an example of that. Hope that helps!

**Comment by oicu0619** [comment]
Thanks for the reply! I have another question about compiling. It says in the document and readme.md that "Every variable is defined before it is used". Is the mutation relaying on that? Does the variable including the output variable of BeginPlainFunctionDefinition, which is, function declaration? If so, how should we process mutually recursive function? thanks for the help!

**Comment by saelo** [comment]
Yeah if a variable is used before it is defined, then the code won't be statically valid and so Fuzzilli will reject/not import it. If such a sample would be accepted, it would probably lead to lots of issues as components such as analyzers, the lifter, or the minimizers all assume that a variable is defined before it is used (and e.g. associate state with a variable when it is defined).
A simple recursive function would work like this
```
v2 <- BeginFunctionDefinition ...
    CallFunction v2
EndFunctionDefinition
```
Mutually recursive functions are possible like this:
```
v0 <- LoadUndefined
v1 <- BeginFunctionDefinition ...
    CallFunction v0
EndFunctionDefinition
v2 <- BeginFunctionDefinition ...
    CallFunction v1
EndFunctionDefinition
Reassign v0, v2
```

**Comment by oicu0619** [comment]
Thanks a lot for the reply! I have some more question about compiling JS to IR:
1. some statements/expressions are not easy to compile to IR, such as call super constructor with spread element; strict async (generator) function; load super computed property , and so on. Could i make some pull request to add some more IR operations? 
2. some of the statements/expressions can be transformed and then compiled into IR, such as optional chaining; destructing assignment; or function parameter default value; do you think it's better to transform JS to fit current IR, or maybe add corresponding IR operations? 
3.  IR expression ConditionalOperation  will not easy to fit the JS like
```
true?x++:x;
```
So, is it better to compile it to if else?

**Comment by oicu0619** [comment]
Also, does it make sense to let Yield/YieldEach IR Operation have 1 Output? Currently they have 0 output. 
For example:
```
function* generator(){
  let x=20;
  x= yield 100;
  yield x;
}
var gen = generator();
gen.next().value
gen.next(1).value; 
```
then the function can be compiled to
```
v0 <- LoadInteger 20;
v1 <- LoadInteger 100;
v2 <- Yield v1;
Reassign v0, v2;
v3 <- Yield v0;
```

**Comment by saelo** [comment]
1. Absolutely, in fact, that'd be great!
2. There is probably no universal answer to that. I think it usually makes sense to add new FuzzIL operations or modify existing ones where JS construct cannot be expressed with the existing operations, as long as that doesn't add too much complexity. Feel free to open separate issues for discussing these in more detail.
3. Right, I think for that you'd probably need to create an `if-else`. The issue is that, currently, FuzzIL doesn't have a concept of an "expression context", which would be blocks where expressions but no statements are allowed (so, probably only non-Block operations). This would e.g. also be needed to https://github.com/googleprojectzero/fuzzilli/issues/8 

Re. `yield`, good point! Could you either create a separate issue to track that (e.g. just "Yield Operation in FuzzIL should have an Output") and copy the example from above, or send a PR if you want to fix that yourself? Thanks!

**Comment by oicu0619** [comment]
Thanks for the reply! 
I will try to send a PR about yield.
