### ISSUE TITLE
Make --deterministicCorpus the default?

### ISSUE THREAD

**Issue by saelo** [googleprojectzero/fuzzilli#228]
I think it would make sense to make `--deterministicCorpus` the default, since it probably improves the quality of the samples kept in the corpus at a relatively low cost (the overhead from the additional executions is probably not higher than the overhead from minimization). Furthermore, this could also allow us to enable background threads for the JS engines (typically used for GC and JIT compilation) which are currently artificially disabled.
One question is whether we then want a `--noDeterministicCorpus` flag instead or if the `--minDeterminismExecs` and `--maxDeterminismExecs` flags are enough.

**Comment by saelo** [comment]
@WilliamParks WDYT?

**Comment by WilliamParks** [comment]
Sounds good to me!

I think having a `--noDeterministicCorpus` flag makes the most sense, as it's the clearest to the user and should be easy to implement.

**Comment by saelo** [comment]
Related PR: https://github.com/googleprojectzero/fuzzilli/pull/237

**Comment by saelo** [comment]
Done: https://github.com/googleprojectzero/fuzzilli/pull/237
