### ISSUE TITLE
A typo in builtin function name

### ISSUE THREAD

**Issue by singleghost** [googleprojectzero/fuzzilli#23]
In CodeGenerators.swift, this line defines some builtin functions.
```
var candidates = Set(["getPrototypeOf", "setPrototypeOf", "isExtensible", "preventExtension", "getOwnPropertyDescriptor", "defineProperty", "has", "get", "set", "deleteProperty", "ownKeys", "apply", "call", "construct"])
```
Shouldn't the `preventExtension` be `preventExtensions` according to the spec?

**Comment by saelo** [comment]
Ah yes correct, thanks! Fixed with https://github.com/googleprojectzero/fuzzilli/commit/4cf15dc993c634c18a3d76df6eeac5927fee7add
