### ISSUE TITLE
[Fuzzer] Testcase "fuzzilli('FUZZILLI_CRASH', 2)" did not crash

### ISSUE THREAD

**Issue by Zon8Research** [googleprojectzero/fuzzilli#234]
Latest commit for both fuzzilli and v8:
Fuzzilli: 10d5db4700b2d02481b916302269025cee9a1f69
V8: 651e1e50e49c24c1f978d769323e400dd0895ee1

Fuzzilli won't start due to:

```
[Fuzzer] Testcase "fuzzilli('FUZZILLI_CRASH', 2)" did not crash
```

```
~/v8/out/fuzzbuild/d8 --allow-natives-syntax
[COV] no shared memory bitmap available, skipping
[COV] edge counters initialized. Shared memory: (null) with 452586 edges
[COV] Additional 0 edges for builtins initialized.
V8 version 9.4.0 (candidate)
d8> fuzzilli('FUZZILLI_CRASH',2)
undefined
```

Note: `fuzzilli('FUZZILLI_CRASH', 1)` and `fuzzilli('FUZZILLI_CRASH', 0)` still work as intended.

**Comment by saelo** [comment]
Can you check if https://github.com/googleprojectzero/fuzzilli/commit/84f9b15937ece08bf722dc644df6f3d507c18d40 fixes it?

**Comment by Zon8Research** [comment]
Yes that fixes it :)
