### ISSUE TITLE
Lifting IR Operation createArray

### ISSUE THREAD

**Issue by oicu0619** [googleprojectzero/fuzzilli#244]
```
v0 <- LoadInteger '1'
v1 <- LoadUndefined
v2 <- CreateArray [v0, v1]
```
will be lifted to 
```
const v2 = [1,];
```
Which means [1].  The comma will be interpreted as trailing comma by JS engine, which will be ignored. Then if i want a array which end with hole, i have to put two ```LoadUndefined``` there.
Is this intends? Thanks!

**Comment by saelo** [comment]
Ah yes, good catch and thanks for the PR, let's continue the discussion there!
