### ISSUE TITLE
Lift IR operation CreateObject

### ISSUE THREAD

**Issue by oicu0619** [googleprojectzero/fuzzilli#246]
Currently ```v1 <- CreateObject ['a':v0]```will lift to ``` v1={a:v0}```
It is OK to change it to lift to ```v1={"a":v0}``` ? it  will be easier to compile JS like https://github.com/tc39/test262/blob/main/test/built-ins/Object/getOwnPropertyDescriptor/15.2.3.3-2-33.js
Thanks!

**Comment by saelo** [comment]
Good point! Yeah I'm fine with just generally lifting as `{"a":v0}`. Alternatively, we could only do it for non-alphanumeric property names:
```swift
if CharacterSet.alphanumerics.isSuperset(of: CharacterSet(charactersIn: propertyName)) {
    // lift as {a:v0}
} else {
    // lift as {"a":v0}
}
```
But maybe that's needlessly complicated/slow?

**Comment by oicu0619** [comment]
Seems to me that for alphanumeric property names, with and without quote is kind of the same thing? https://tc39.es/ecma262/#sec-object-initializer-runtime-semantics-evaluation . They are all used as string values. So maybe it's fine to put all property names inside quotes?

**Comment by saelo** [comment]
Yep sounds good, so let's go with that! Can you send a PR?
