### ISSUE TITLE
Failed build Fuzzilli compiler

### ISSUE THREAD

**Issue by areuu** [googleprojectzero/fuzzilli#259]
I'm following the README and Dockerfile, still can't build success.

...
➜  Compiler git:(main) opam pin add -y flow_parser https://github.com/facebook/flow.git
[flow_parser.0.80.0] synchronised from git+https://github.com/facebook/flow.git
flow_parser is now pinned to git+https://github.com/facebook/flow.git (version 0.159.0)

Sorry, no solution found: there seems to be a problem with your request.

[NOTE] Pinning command successful, but your installed packages may be out of
       sync.

when typed "esy build" 
...
    ocamlfind ocamldep -package ppx_gen_rec -package ppx_deriving.eq -package ppx_deriving.ord -package ppx_deriving.show -package sedlex.ppx -package wtf8 -modules src/parser/pattern_cover.ml > src/parser/pattern_cover.ml.depends
    ocamlfind ocamlc -c -safe-string -w A -warn-error A -strict-sequence -w -39 -package ppx_gen_rec -package ppx_deriving.eq -package ppx_deriving.ord -package ppx_deriving.show -package sedlex.ppx -package wtf8 -w -4-6-29-35-42-44-48-50 -I src/parser -I src/third-party/sedlex -I src/parser_utils/output/__tests__/js_layout_generator -o src/parser/pattern_cover.cmo src/parser/pattern_cover.ml
    ocamlfind ocamldep -package ppx_gen_rec -package ppx_deriving.eq -package ppx_deriving.ord -package ppx_deriving.show -package sedlex.ppx -package wtf8 -modules src/parser/flow_lexer.ml > src/parser/flow_lexer.ml.depends
    ocamlfind ocamldep -package ppx_deriving.eq -package ppx_deriving.ord -package ppx_deriving.show -package sedlex.ppx -package wtf8 -package base -package visitors.runtime -package core_kernel -package ppx_deriving -package ppx_deriving.iter -package ppx_deriving.map -package dtoa -modules src/third-party/sedlex/flow_sedlexing.mli > src/third-party/sedlex/flow_sedlexing.mli.depends
    + ocamlfind ocamldep -package ppx_deriving.eq -package ppx_deriving.ord -package ppx_deriving.show -package sedlex.ppx -package wtf8 -package base -package visitors.runtime -package core_kernel -package ppx_deriving -package ppx_deriving.iter -package ppx_deriving.map -package dtoa -modules src/third-party/sedlex/flow_sedlexing.mli > src/third-party/sedlex/flow_sedlexing.mli.depends
    ocamlfind: Package `base' not found
    Command exited with code 2.
    make: *** [Makefile:53: build-parser] Error 10
    make: Leaving directory '/home/uuu/fuzzjs/fuzzilli/Compiler/_esy/default/store/b/flow__parser-27421cfd/src/parser'
    error: command failed: 'make' '-C' 'src/parser' 'build-parser' (exited with 2)
    esy-build-package: exiting with errors above...
    
  building flow_parser@link:/home/uuu/.opam/4.10.2/.opam-switch/sources/flow_parser/flow_parser.opam

**Comment by areuu** [comment]
I used ocaml 4.10.2, but still failed.

**Comment by areuu** [comment]
Ok, I fix it.

**Comment by bernhl** [comment]
I just encountered the same issue, pinning flow to v0.156.0 via `opam pin add -y flow_parser https://github.com/facebook/flow.git#v0.156.0` solves it for me.

**Comment by areuu** [comment]
I solved it, thanks.
