### ISSUE TITLE
Add option to discard non-deterministic programs

### ISSUE THREAD

**Issue by saelo** [googleprojectzero/fuzzilli#26]
Add a new command line flag `--deterministicCorpus` which, when set, causes FuzzerCore to rerun every newly discovered interesting program to see if it behaves deterministically (i.e. triggers the same new behaviour a second time).  If not, the sample is discarded right away.

Previously, non-deterministic samples would likely be discarded during import in a worker or master as that would cause the program to be re-executed. However, since the introduction of the new synchronization mechanism, this is no longer the case for a large part of the corpus. As such, it might make sense to "manually" filter out non-deterministic samples.

**Comment by adrian-rt** [comment]
I was searching how does Fuzzilli treat non-deterministic behaviour in js engines and all I can see from the source is that it doesn't....? If we run the same js file under JSC for example, it will always result in new coverage due to threads order execution for example....Fuzzili simply considers this as new coverage even though it's the same file, or am I missing something? thanks!

**Comment by saelo** [comment]
Hi! First off, note that Fuzzilli [turns off things like background threads](https://github.com/googleprojectzero/fuzzilli/blob/master/Sources/FuzzilliCli/Profiles/JSCProfile.swift#L36) and generally seeks for the engine to [be as deterministic as possible](https://github.com/googleprojectzero/fuzzilli/blob/bc51249457b97480cffc31cdc2cf66fb2d05616b/Sources/FuzzilliCli/Profiles/V8Profile.swift#L32). Also, non-deterministic edges will only be treated as interesting once (and thus the sample added to the corpus), and that will mostly happen in the early phase of fuzzing. Finally, Fuzzilli sort of naturally filters out non-deterministic samples, at least in [distributed fuzzing mode](https://github.com/googleprojectzero/fuzzilli/tree/master/Cloud/GCE), since samples found by workers are re-executed on the master instances before being added to the "global" corpus. As such, in the typical case of an interesting sample being found by a worker, it has to reproduce twice (at its master and the root) for it to be added to the global corpus.
This issue is for evaluating even more aggressive filtering of non-deterministic behaviour. When I briefly attempted this some time ago, it didn't result in any noticeable improvements, but it's worth retesting at some point.
Hope that answers your question!

**Comment by WilliamParks** [comment]
One way to implement this is discussed [here](https://github.com/googleprojectzero/fuzzilli/pull/171#discussion_r525947709). Periodically, each fuzzer instance could clear its coverage data, and import all samples. First, this would remove undeterministic samples. Additionally, the order in which samples are reimported could affect which ones are included. For example, the edges of a recent sample could be a superset of a sample found early in the fuzzing run. Alternatively, starting the reimport by size would prioritize simpler samples, like is done currently when [importing a corpus](https://github.com/googleprojectzero/fuzzilli/blob/master/Sources/FuzzilliCli/main.swift#L471).

**Comment by saelo** [comment]
This was added as part of https://github.com/googleprojectzero/fuzzilli/pull/171
