### ISSUE TITLE
Import corpus without state

### ISSUE THREAD

**Issue by wbowling** [googleprojectzero/fuzzilli#27]
Could `evaluatorState` be made optional or add a flag to ignore an incompatible state when importing?

It can be useful to import a previous corpus when testing a new version

**Comment by saelo** [comment]
Hmm good point. So another possible approach I see is to slightly change the logic of Fuzzer.importState to do the following:
* try to import the evaluator state
* if that succeeds, try importing the corpus state
* if any of the above fail, print a info or warning message, potentially revert any imported state, and import the corpus via Fuzzer.importCorpus (which will execute every sample in it)
That way we wouldn't need new cli flags etc.
What do you think?

**Comment by wbowling** [comment]
> * What do you think?

Yeah that sounds like a good solution, then it should work for both cases without the need for another flag
