### ISSUE TITLE
[REPRL] Script execution failed: Child unexpectedly terminated with signal 11 

### ISSUE THREAD

**Issue by Limesss** [googleprojectzero/fuzzilli#283]
1. when i finish the lastest Patch for JerryJS , i start it will crash all the time , not real crash ,  child crash. has anyone do the same?
2. 
3. ------------------------------
4. [JavaScriptEnvironment] Have 5 custom property names: ["c", "e", "d", "b", "a"]
5. [JavaScriptEnvironment] Have 4 custom method names: ["p", "m", "o", "n"]
6. [Fuzzer] Initialized
7. [Fuzzer] Recommended timeout: at least 100ms. Current timeout: 250ms
8. [Fuzzer] Startup tests finished successfully
9. [Fuzzer] Let's go!
10. ########## Unique Crash Found ##########
11. function placeholder(){}
12. function main() {
13. var v4 = [952523.6408286022,952523.6408286022,String,952523.6408286022];
14. var v5 = [127,127];
15. var v6 = [String,127,String,127,String,String,"match",String];
16. var v7 = {"constructor":String};
17. var v8 = {};
18. var v10 = Object();
19. }
20. main();
21. // CRASH INFO
22. // ==========
23. // TERMSIG: 11
24. // STDERR:
25. 
26. ########## Unique Crash Found ##########
27. function placeholder(){}
28. function main() {
29. String.prototype = 952523.6408286022;
30. "match".valueOf = String;
31. var v4 = 127 - String;
32. var v6 = Object();
33. var v7 = Object;
34. var v8 = [String,127,String,127,String,String,String,String];
35. var v9 = 6;
36. }
37. main();
38. // CRASH INFO
39. // ==========
40. // TERMSIG: 11
41. // STDERR:
42. // SyntaxError: Invalid (unexpected) character [<anonymous>:1:345]
43. 
44. [REPRL] Script execution failed: Child unexpectedly terminated with signal 11 between executions. Retrying in 1 second...
45. [REPRL] Script execution failed: Child unexpectedly terminated with signal 11 between executions. Retrying in 1 second...
46. ########## Unique Crash Found ##########
47. function placeholder(){}
48. function main() {
49. var v1 = "match";
50. var v4 = [551811.7789949593,551811.7789949593,551811.7789949593,551811.7789949593];
51. var v5 = [127,127];
52. var v6 = [Object,127,Object,127,Object,Object,Object,Object];
53. var v7 = {"b":v5};
54. var v8 = {};
55. var v10 = Object();
56. }
57. main();
58. // CRASH INFO
59. // ==========
60. // TERMSIG: 11
61. // STDERR:
62. 
63. ########## Unique Crash Found ##########
64. function placeholder(){}
65. function main() {
66. var v1 = "match";
67. var v3 = 952523.6408286022;
68. var v4 = [127,127];
69. var v6 = Object();
70. var v7 = [String,127,String,127,String,String,String,String];
71. var v8 = {"constructor":v4};
72. var v10 = Object();
73. }
74. main();
75. // CRASH INFO
76. // ==========
77. // TERMSIG: 11
78. // STDERR:
79. ------------------------------
80. this is dmesg info ...
81. ------------------------------
82. [348404.742119] traps: jerry[352904] general protection fault ip:7fcee3f786a7 sp:7ffc46e39d68 error:0 in libc-2.31.so[7fcee3e12000+178000]
83. [348404.997745] jerry[352906]: segfault at 20 ip 00007f7cf19de6a7 sp 00007fff21b3c6a8 error 4 in libc-2.31.so[7f7cf1878000+178000]
84. [348404.997751] Code: 85 c0 0f 85 eb 00 00 00 48 83 c7 20 83 e1 1f 48 83 e7 e0 eb 42 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 83 e1 1f 48 83 e7 e0 <c5> fd 74 0f c5 fd d7 c1 d3 f8 85 c0 74 1b f3 0f bc c0 48 01 f8 48
85. [348405.307191] traps: jerry[352908] general protection fault ip:7f82e3f4f6a7 sp:7fffa1d8d798 error:0 in libc-2.31.so[7f82e3de9000+178000]
86. [348405.577689] traps: jerry[352911] general protection fault ip:425583 sp:7ffe46a679c0 error:0 in jerry[404000+a8000]
87. [348406.873477] jerry[352932]: segfault at 7fffd8669938 ip 0000000000425583 sp 00007fff180b64a0 error 4 in jerry[404000+a8000]
88. [348406.873483] Code: 00 e8 2a 1b 00 00 48 8d bd 70 ff ff ff e8 18 0e 00 00 83 bd 78 ff ff ff 00 0f 84 48 02 00 00 41 bf 01 00 00 00 43 8b 44 fd f8 <49> 8b 1c c4 66 43 83 7c fd fe 01 75 6c 48 89 df e8 a3 4e 00 00 41
89. [348407.160486] traps: jerry[352934] general protection fault ip:7fe6543aa6a7 sp:7ffc4de2d9d8 error:0 in libc-2.31.so[7fe654244000+178000]
90. [348407.428402] traps: jerry[352936] general protection fault ip:7f8d296786a7 sp:7ffecf9258d8 error:0 in libc-2.31.so[7f8d29512000+178000]
91. [348409.008911] show_signal: 1 callbacks suppressed
92. [348409.008913] traps: jerry[352953] general protection fault ip:7fddbcde16a7 sp:7ffd188e7138 error:0 in libc-2.31.so[7fddbcc7b000+178000]
93. [348409.321060] traps: jerry[352955] general protection fault ip:7fb5440d06a7 sp:7fff65d2a828 error:0 in libc-2.31.so[7fb543f6a000+178000]
94. [348409.591864] traps: jerry[352957] general protection fault ip:7fbce6bac675 sp:7fffc4ab1a08 error:0 in libc-2.31.so[7fbce6a46000+178000]
95. [348409.862859] traps: jerry[352959] general protection fault ip:425583 sp:7ffdba3dde40 error:0 in jerry[404000+a8000]
96. [348410.139865] traps: jerry[352967] general protection fault ip:425583 sp:7fff4654d350 error:0 in jerry[404000+a8000]
97. [348410.414398] traps: jerry[352969] general protection fault ip:7fef5f3d46a7 sp:7ffe96aa2ba8 error:0 in libc-2.31.so[7fef5f26e000+178000]
98. [348410.690825] traps: jerry[352971] general protection fault ip:7f2b8fe186a7 sp:7ffde17ba378 error:0 in libc-2.31.so[7f2b8fcb2000+178000]
99. [348410.963403] traps: jerry[352973] general protection fault ip:7fbd8b1846a7 sp:7fff2ef27898 error:0 in libc-2.31.so[7fbd8b01e000+178000]
100. [348411.232448] traps: jerry[352975] general protection fault ip:7fea5c3766a7 sp:7ffc5b7bbd08 error:0 in libc-2.31.so[7fea5c210000+178000]
101. [348411.507527] traps: jerry[352977] general protection fault ip:7f0ba1fc06a7 sp:7ffe7f2ae598 error:0 in libc-2.31.so[7f0ba1e5a000+178000]
102. [348414.055465] show_signal: 8 callbacks suppressed
103. [348414.055467] traps: jerry[353023] general protection fault ip:7f285f1c56a7 sp:7fff01a828b8 error:0 in libc-2.31.so[7f285f05f000+178000]
104. [348414.320315] traps: jerry[353031] general protection fault ip:7f78a38456a7 sp:7ffcd773a1a8 error:0 in libc-2.31.so[7f78a36df000+178000]
105. [348414.594850] traps: jerry[353033] general protection fault ip:7f6353df66a7 sp:7ffdaca787d8 error:0 in libc-2.31.so[7f6353c90000+178000]
106. [348414.862010] traps: jerry[353035] general protection fault ip:7fef34b176a7 sp:7ffda03d2598 error:0 in libc-2.31.so[7fef349b1000+178000]
107. [348415.142351] traps: jerry[353037] general protection fault ip:7f2a4e8586a7 sp:7ffd42796e28 error:0 in libc-2.31.so[7f2a4e6f2000+178000]
108. [348416.185495] jerry[353040]: segfault at 7ffdb1e3edf8 ip 0000000000425583 sp 00007ffc3035c360 error 4 in jerry[404000+a8000]
109. [348416.185501] Code: 00 e8 2a 1b 00 00 48 8d bd 70 ff ff ff e8 18 0e 00 00 83 bd 78 ff ff ff 00 0f 84 48 02 00 00 41 bf 01 00 00 00 43 8b 44 fd f8 <49> 8b 1c c4 66 43 83 7c fd fe 01 75 6c 48 89 df e8 a3 4e 00 00 41
110. [348416.459543] traps: jerry[353048] general protection fault ip:425583 sp:7ffdc197f810 error:0 in jerry[404000+a8000]
111. [348416.730702] jerry[353062]: segfault at 7ffc369007b8 ip 0000000000425583 sp 00007ffc060fff20 error 4 in jerry[404000+a8000]
112. [348416.730709] Code: 00 e8 2a 1b 00 00 48 8d bd 70 ff ff ff e8 18 0e 00 00 83 bd 78 ff ff ff 00 0f 84 48 02 00 00 41 bf 01 00 00 00 43 8b 44 fd f8 <49> 8b 1c c4 66 43 83 7c fd fe 01 75 6c 48 89 df e8 a3 4e 00 00 41
113. ------------------------------

**Comment by saelo** [comment]
I think this is the same issue as https://github.com/googleprojectzero/fuzzilli/issues/120? I'll close it for now, but feel free to reopen if this is still an issue.
