### ISSUE TITLE
--importCorpus

### ISSUE THREAD

**Issue by cc009071** [googleprojectzero/fuzzilli#3]
how to use this option?

when i supply a path, such as: --importCorpus=dir_path
output err: 
`the operation could not be completed`  at line 
`Sources/FuzzilliCli/main.swift#L175`

**Comment by saelo** [comment]
You have to give it a .json file that is [produced by Storage.swift](https://github.com/googleprojectzero/fuzzilli/blob/f6edda203f1c6bc3b38af49812f75b8f7102f9f7/Sources/Fuzzilli/Modules/Storage.swift#L68) when you set --exportCorups=true. Importing existing JavaScript code is not currently supported. See also https://github.com/googleprojectzero/fuzzilli/issues/4.
