### ISSUE TITLE
Patch Hunk failed on latest Webkit source

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#304]
[jsc.cpp.rej.txt](https://github.com/googleprojectzero/fuzzilli/files/7654727/jsc.cpp.rej.txt)
This Hunk #8 fails to apply "--- Source/JavaScriptCore/jsc.cpp
+++ Source/JavaScriptCore/jsc.cpp
@@ -1230,18 +1135,6 @@ JSObject* GlobalObject::moduleLoaderCreateImportMetaProperties(JSGlobalObject* g
     return metaProperties;
 }
 
-static int numPendingRejectedPromises = 0;
-void GlobalObject::promiseRejectionTracker(JSGlobalObject*, JSPromise*, JSPromiseRejectionOperation operation) {
-    switch (operation) {
-    case JSPromiseRejectionOperation::Reject:
-        numPendingRejectedPromises += 1;
-        break;
-    case JSPromiseRejectionOperation::Handle:
-        numPendingRejectedPromises -= 1;
-        break;
-    }
-}
-
 static CString cStringFromViewWithString(JSGlobalObject* globalObject, ThrowScope& scope, StringViewWithUnderlyingString& viewWithString)
 {
     Expected<CString, UTF8ConversionError> expectedString = viewWithString.view.tryGetUtf8();"

any suggestion please?

**Comment by turnerrocks1** [comment]
[jsc.txt](https://github.com/googleprojectzero/fuzzilli/files/7655137/jsc.txt)

here's the current version of webkit's most updated jsc.cpp if that helps...

**Comment by turnerrocks1** [comment]
[webbbbbb.txt](https://github.com/googleprojectzero/fuzzilli/files/7656801/webbbbbb.txt)
Fixed: For anyone that downloaded the latest webkit source code and applying the original patch failed... then download this patch file I made "webbbbbb.txt" and rename it "webkit.patch" place it in the root of the Webkit folder and open up your linux terminal and type "patch -p1 < webkit.patch" hope this helps anyone that needed it!

**Comment by turnerrocks1** [comment]
Update #2 sooo after fixing up the webkit.patch and running fuzzbuild.sh I found that i guess after this was made that cStringFromViewWithString() was deleted or "regressed" so i made a workaround whether it was intentional or not but the new function is now toCString() I'll be adding a new updated patch in a few minutes that'll fix this issue!!!!

**Comment by turnerrocks1** [comment]
[webbbbbb1.patch.txt](https://github.com/googleprojectzero/fuzzilli/files/7656874/webbbbbb1.patch.txt)

**Comment by saelo** [comment]
Thanks!
