### ISSUE TITLE
about iterator assignment value in the  for loop

### ISSUE THREAD

**Issue by maldiohead** [googleprojectzero/fuzzilli#305]
Hi, I just write a  programbuilder Templates, I want for write a for loop and assign value iteratored , but I review the code didn't found the way how to write the template to generate the code below:
```
for(v1=0;v1<100;v1++)
{ 
let v2[v1]=1;  // ----------->How should I write the template  to generate the code like this line?
}
```

**Comment by saelo** [comment]
It should be something like
```swift
let b = ... // Get a ProgramBuilder

let start = b.loadInt(0)
let end = b.loadInt(100)
let step = b.loadInt(1)
b.forLoop(start, .lessThan, end, .Add, step) { v1 in
    b.storeComputedProperty(b.loadInt(1), as: v1, on: v2)
}
```
So you get the iterator variable as input to your body closure for the `forLoop`
