### ISSUE TITLE
Implement worker synchronization over IPC

### ISSUE THREAD

**Issue by saelo** [googleprojectzero/fuzzilli#31]
Similar to the [NetworkSync module](https://github.com/googleprojectzero/fuzzilli/blob/master/Sources/Fuzzilli/Modules/NetworkSync.swift) but over some IPC channel instead of TCP sockets.

**Comment by minhtt159** [comment]
I'm having problem with the synchronization. 
As far as I understand, the master control stand in the middle and push messages to the workers. But the master have to fuzz the program as well. When the number of workers is large (20 instances in my case), the master is overloaded and having some pending tasks.
I would like to suggest the solution that the master is responsible to sending messages & organize samples only, and perhaps network module can use another thread if possible.

**Comment by saelo** [comment]
Hi! I usually fuzz with multiple levels of master instances, for example one "root" master, then 8-16 intermediate masters, then 16-32 workers per intermediate master. That said it probably still makes sense to add and evaluate a new runtime option that causes master instances to not do any fuzzing on their own and only do synchronization. I'll look into that.

**Comment by saelo** [comment]
Closing this now since it's not clear what the benefit would be since we have both TCP-based synchronization and inter-thread synchronization.
