### ISSUE TITLE
Docker image crashes

### ISSUE THREAD

**Issue by OrenGitHub** [googleprojectzero/fuzzilli#316]
Hi, I followed the instruction in [fuzzilli/cloud/docker][1] and everything went smooth.
When I try to launch it on a sample javascript file it crashes:
```
root@a2c68e9bd455:/home/fuzzer# cat input.js
console.log('Hello World');

root@a2c68e9bd455:/home/fuzzer# ./Fuzzilli --profile=v8 input.js
[Fuzzer] Please run: sudo sysctl -w 'kernel.core_pattern=|/bin/false'
[Fuzzer] Shutting down due to fatal error
```
Any ideas how to solve it? thanks !

[1]: https://github.com/googleprojectzero/fuzzilli/tree/main/Cloud/Docker#readme

**Comment by saelo** [comment]
I guess this is a duplicate of https://github.com/googleprojectzero/fuzzilli/issues/320
