### ISSUE TITLE
symbol error

### ISSUE THREAD

**Issue by ttkqqr** [googleprojectzero/fuzzilli#32]
hello saelo:
I just build d8 with this v8.patch but get error:
symbol lookup error: /home/******/libc++.so: undefined symbol: __sanitizer_cov_trace_pc_guard_init

but I have built it successfully on d8 version 7.5.288.22 with this patch in commit cfa57b661cc1996cbebbcabe0d4bd9e0a2c3eaae.

I search in the internet and can not solve this error, may you give me some help or advice?

**Comment by Hckmaple** [comment]
update: failed then build v8 version 7.5.288.30 with v8.patch
