### ISSUE TITLE
newest patch for Webkit

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#335]
diff --git a/Source/JavaScriptCore/jsc.cpp b/Source/JavaScriptCore/jsc.cpp
index 1925107c888a..411f5bf3ec28 100644
--- a/Source/JavaScriptCore/jsc.cpp
+++ b/Source/JavaScriptCore/jsc.cpp
@@ -166,7 +166,96 @@ struct MemoryFootprint {
 #if !defined(PATH_MAX)
 #define PATH_MAX 4096
 #endif
+//
+// BEGIN FUZZING CODE
+//
 
+#include <fcntl.h>
+#include <stdlib.h>
+#include <stdio.h>
+#include <string.h>
+#include <sys/wait.h>
+#include <sys/mman.h>
+
+#define REPRL_CRFD 100
+#define REPRL_CWFD 101
+#define REPRL_DRFD 102
+#define REPRL_DWFD 103
+#define REPRL_MAX_DATA_SIZE (16*1024*1024)
+
+#define SHM_SIZE 0x100000
+#define MAX_EDGES ((SHM_SIZE - 4) * 8)
+
+#define CHECK(cond) if (!(cond)) { fprintf(stderr, "\"" #cond "\" failed\n"); exit(EXIT_FAILURE); }
+
+// Shared memory buffer with the parent.
+char* reprl_input_data;
+
+struct shmem_data {
+    uint32_t num_edges;
+    unsigned char edges[];
+};
+
+struct shmem_data* __shmem;
+uint32_t *__edges_start, *__edges_stop;
+
+void __sanitizer_cov_reset_edgeguards() {
+    uint64_t N = 0;
+    for (uint32_t *x = __edges_start; x < __edges_stop && N < MAX_EDGES; x++)
+        *x = ++N;
+}
+
+extern "C" void __sanitizer_cov_trace_pc_guard_init(uint32_t *start, uint32_t *stop) {
+    // Avoid duplicate initialization
+    if (start == stop || *start)
+        return;
+
+    if (__edges_start != NULL || __edges_stop != NULL) {
+        fprintf(stderr, "Coverage instrumentation is only supported for a single module\n");
+        _exit(-1);
+    }
+
+    __edges_start = start;
+    __edges_stop = stop;
+
+    // Map the shared memory region
+    const char* shm_key = getenv("SHM_ID");
+    if (!shm_key) {
+        puts("[COV] no shared memory bitmap available, skipping");
+        __shmem = (struct shmem_data*) malloc(SHM_SIZE);
+    } else {
+        int fd = shm_open(shm_key, O_RDWR, S_IREAD | S_IWRITE);
+        if (fd <= -1) {
+            fprintf(stderr, "Failed to open shared memory region: %s\n", strerror(errno));
+            _exit(-1);
+        }
+
+        __shmem = (struct shmem_data*) mmap(0, SHM_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
+        if (__shmem == MAP_FAILED) {
+            fprintf(stderr, "Failed to mmap shared memory region\n");
+            _exit(-1);
+        }
+    }
+
+    __sanitizer_cov_reset_edgeguards();
+
+    __shmem->num_edges = stop - start;
+    printf("[COV] edge counters initialized. Shared memory: %s with %u edges\n", shm_key, __shmem->num_edges);
+}
+
+extern "C" void __sanitizer_cov_trace_pc_guard(uint32_t *guard) {
+    // There's a small race condition here: if this function executes in two threads for the same
+    // edge at the same time, the first thread might disable the edge (by setting the guard to zero)
+    // before the second thread fetches the guard value (and thus the index). However, our
+    // instrumentation ignores the first edge (see libcoverage.c) and so the race is unproblematic.
+    uint32_t index = *guard;
+    __shmem->edges[index / 8] |= 1 << (index % 8);
+    *guard = 0;
+}
+
+//
+// END FUZZING CODE
+//
 using namespace JSC;
 
 namespace {
@@ -382,6 +471,7 @@ static JSC_DECLARE_HOST_FUNCTION(functionFlashHeapAccess);
 static JSC_DECLARE_HOST_FUNCTION(functionDisableRichSourceInfo);
 static JSC_DECLARE_HOST_FUNCTION(functionMallocInALoop);
 static JSC_DECLARE_HOST_FUNCTION(functionTotalCompileTime);
+static JSC_DECLARE_HOST_FUNCTION(functionFuzzilli);
 
 static JSC_DECLARE_HOST_FUNCTION(functionSetUnhandledRejectionCallback);
 static JSC_DECLARE_HOST_FUNCTION(functionAsDoubleNumber);
@@ -401,7 +491,8 @@ struct Script {
 
     enum class CodeSource {
         File,
-        CommandLine
+        CommandLine,
+        REPRL
     };
 
     StrictMode strictMode;
@@ -435,6 +526,7 @@ public:
     String m_profilerOutput;
     String m_uncaughtExceptionName;
     bool m_interactive { false };
+    bool m_reprl { false };
     bool m_dump { false };
     bool m_module { false };
     bool m_exitCode { false };
@@ -682,6 +774,8 @@ private:
         addFunction(vm, "mallocInALoop", functionMallocInALoop, 0);
         addFunction(vm, "totalCompileTime", functionTotalCompileTime, 0);
 
+        addFunction(vm, "fuzzilli", functionFuzzilli, 2);
+
         addFunction(vm, "setUnhandledRejectionCallback", functionSetUnhandledRejectionCallback, 1);
 
         addFunction(vm, "asDoubleNumber", functionAsDoubleNumber, 1);
@@ -730,6 +824,7 @@ private:
     static Identifier moduleLoaderResolve(JSGlobalObject*, JSModuleLoader*, JSValue, JSValue, JSValue);
     static JSInternalPromise* moduleLoaderFetch(JSGlobalObject*, JSModuleLoader*, JSValue, JSValue, JSValue);
     static JSObject* moduleLoaderCreateImportMetaProperties(JSGlobalObject*, JSModuleLoader*, JSValue, JSModuleRecord*, JSValue);
+    static void promiseRejectionTracker(JSGlobalObject*, JSPromise*, JSPromiseRejectionOperation);
 
     static void reportUncaughtExceptionAtEventLoop(JSGlobalObject*, Exception*);
 };
@@ -753,7 +848,7 @@ const GlobalObjectMethodTable GlobalObject::s_globalObjectMethodTable = {
     &moduleLoaderFetch,
     &moduleLoaderCreateImportMetaProperties,
     nullptr, // moduleLoaderEvaluate
-    nullptr, // promiseRejectionTracker
+    &promiseRejectionTracker,
     &reportUncaughtExceptionAtEventLoop,
     &currentScriptExecutionOwner,
     &scriptExecutionStatus,
@@ -1248,6 +1343,18 @@ JSObject* GlobalObject::moduleLoaderCreateImportMetaProperties(JSGlobalObject* g
     return metaProperties;
 }
 
+static int numPendingRejectedPromises = 0;
+void GlobalObject::promiseRejectionTracker(JSGlobalObject*, JSPromise*, JSPromiseRejectionOperation operation) {
+    switch (operation) {
+    case JSPromiseRejectionOperation::Reject:
+        numPendingRejectedPromises += 1;
+        break;
+    case JSPromiseRejectionOperation::Handle:
+        numPendingRejectedPromises -= 1;
+        break;
+    }
+}
+
 template <typename T>
 static CString toCString(JSGlobalObject* globalObject, ThrowScope& scope, T& string)
 {
@@ -1318,6 +1425,55 @@ JSC_DEFINE_HOST_FUNCTION(functionPrettyPrint, (JSGlobalObject* globalObject, Cal
     return printInternal(globalObject, callFrame, stdout, true);
 }
 
+// We have to assume that the fuzzer will be able to call this function e.g. by
+// enumerating the properties of the global object and eval'ing them. As such
+// this function is implemented in a way that requires passing some magic value
+// as first argument (with the idea being that the fuzzer won't be able to
+// generate this value) which then also acts as a selector for the operation
+// to perform.
+JSC_DEFINE_HOST_FUNCTION(functionFuzzilli, (JSGlobalObject* globalObject, CallFrame* callFrame))
+{
+    VM& vm = globalObject->vm();
+    auto scope = DECLARE_THROW_SCOPE(vm);
+    if (!callFrame->argument(0).isString()) {
+        // We directly require a string as argument for simplicity
+        return JSValue::encode(jsUndefined());
+    }
+    auto operation = callFrame->argument(0).toString(globalObject)->value(globalObject);
+    RETURN_IF_EXCEPTION(scope, encodedJSValue());
+
+    if (operation == "FUZZILLI_CRASH") {
+        auto arg = callFrame->argument(1).toInt32(globalObject);
+        RETURN_IF_EXCEPTION(scope, encodedJSValue());
+        switch (arg) {
+            case 0:
+                *((int*)0x41414141) = 0x1337;
+                break;
+            case 1:
+                RELEASE_ASSERT(0);
+                break;
+            case 2:
+                ASSERT(0);
+                break;
+        }
+    } else if (operation == "FUZZILLI_PRINT") {
+        static FILE* fzliout = fdopen(REPRL_DWFD, "w");
+        if (!fzliout) {
+            fprintf(stderr, "Fuzzer output channel not available, printing to stdout instead\n");
+            fzliout = stdout;
+        }
+
+        String string = callFrame->argument(1).toWTFString(globalObject);
+        RETURN_IF_EXCEPTION(scope, { });
+        auto cString = toCString(globalObject, scope, string);
+        RETURN_IF_EXCEPTION(scope, { });
+        fprintf(fzliout, "%s\n", cString.data());
+        fflush(fzliout);
+    }
+
+    return JSValue::encode(jsUndefined());
+}
+
 JSC_DEFINE_HOST_FUNCTION(functionDebug, (JSGlobalObject* globalObject, CallFrame* callFrame))
 {
     VM& vm = globalObject->vm();
@@ -3182,7 +3338,15 @@ static void runWithOptions(GlobalObject* globalObject, CommandLine& options, boo
     for (size_t i = 0; i < scripts.size(); i++) {
         JSInternalPromise* promise = nullptr;
         bool isModule = options.m_module || scripts[i].scriptType == Script::ScriptType::Module;
-        if (scripts[i].codeSource == Script::CodeSource::File) {
+        if (scripts[i].codeSource == Script::CodeSource::REPRL) {
+            size_t script_size;
+            CHECK(read(REPRL_CRFD, &script_size, 8) == 8);
+            CHECK(script_size < REPRL_MAX_DATA_SIZE);
+            scriptBuffer.resize(script_size);
+            char* ptr = scriptBuffer.data();
+            memcpy(ptr, reprl_input_data, script_size);
+            fileName = "[REPRL]"_s;
+        } else if (scripts[i].codeSource == Script::CodeSource::File) {
             fileName = String { scripts[i].argument };
             if (scripts[i].strictMode == Script::StrictMode::Strict)
                 scriptBuffer.append("\"use strict\";\n", strlen("\"use strict\";\n"));
@@ -3337,6 +3501,7 @@ static NO_RETURN void printUsageStatement(bool help = false)
     fprintf(stderr, "  -f         Specifies a source file (deprecated)\n");
     fprintf(stderr, "  -h|--help  Prints this help message\n");
     fprintf(stderr, "  -i         Enables interactive mode (default if no files are specified)\n");
+    fprintf(stderr, "  --reprl    Enables REPRL mode (used by the Fuzzilli fuzzer)\n");
     fprintf(stderr, "  -m         Execute as a module\n");
 #if OS(UNIX)
     fprintf(stderr, "  -s         Installs signal handlers that exit on a crash (Unix platforms only, lldb will not work with this option) \n");
@@ -3422,6 +3587,11 @@ void CommandLine::parseArguments(int argc, char** argv)
             m_interactive = true;
             continue;
         }
+        if (!strcmp(arg, "--reprl")) {
+            m_reprl = true;
+            m_scripts.append(Script(Script::StrictMode::Sloppy, Script::CodeSource::REPRL, Script::ScriptType::Script, nullptr));
+            continue;
+        }
         if (!strcmp(arg, "-d")) {
             m_dump = true;
             continue;
@@ -3612,7 +3782,37 @@ int runJSC(const CommandLine& options, bool isWorker, const Func& func)
 #endif
 
     int result;
-    bool success = true;
+    bool success;
+
+    // Let parent know we are ready
+    if (options.m_reprl) {
+        char helo[] = "HELO";
+        CHECK(write(REPRL_CWFD, helo, 4) == 4);
+        CHECK(read(REPRL_CRFD, helo, 4) == 4);
+
+        if (memcmp(helo, "HELO", 4) != 0) {
+            fprintf(stderr, "[REPRL] Invalid response from parent\n");
+            exit(EXIT_FAILURE);
+        }
+
+        // Mmap the data input buffer.
+        reprl_input_data = (char*)mmap(0, REPRL_MAX_DATA_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, REPRL_DRFD, 0);
+        CHECK(reprl_input_data != MAP_FAILED);
+    }
+
+    do {
+    // Keep indention for easier diffing
+    if (options.m_reprl) {
+        unsigned action;
+        CHECK(read(REPRL_CRFD, &action, 4) == 4);
+        if (action != 'cexe') {
+            fprintf(stderr, "[REPRL] Unknown action: %u\n", action);
+            exit(EXIT_FAILURE);
+        }
+    }
+
+    success = true;
+
     GlobalObject* globalObject = nullptr;
     {
         JSLockHolder locker(vm);
@@ -3626,7 +3826,7 @@ int runJSC(const CommandLine& options, bool isWorker, const Func& func)
     vm.deferredWorkTimer->runRunLoop();
     {
         JSLockHolder locker(vm);
-        if (options.m_interactive && success)
+        if (!options.m_reprl && options.m_interactive && success)
             runInteractive(globalObject);
     }
 
@@ -3695,6 +3895,23 @@ int runJSC(const CommandLine& options, bool isWorker, const Func& func)
         dataLogLn(*vm.jitSizeStatistics);
 #endif
 
+    if (options.m_reprl) {
+        // In REPRL mode, stdout and stderr may be regular files, so we need to fflush them here.
+        fflush(stdout);
+        fflush(stderr);
+
+        // Check if any rejected promises weren't handled
+        if (numPendingRejectedPromises > 0) {
+            result = 1;
+            numPendingRejectedPromises = 0;
+        }
+
+        int status = (result & 0xff) << 8;
+        CHECK(write(REPRL_CWFD, &status, 4) == 4);
+        __sanitizer_cov_reset_edgeguards();
+    }
+    } while (options.m_reprl);
+
     vm.codeCache()->write(vm);
 
     if (options.m_destroyVM || isWorker) {

**Comment by 0x41c** [comment]
Could you make a PR and change the REVISION file located in the JavaScriptCore target directory?

I also was making a patch for this because it looks like the extern "c" symbols don't have proper function prototypes. However, I can't test it because my JSC keeps crashing with some missing symbol in the DissallowGC class:
```
dyld[86363]: Symbol not found: __ZN3JSC10DisallowGC19s_scopeReentryCountE
  Referenced from: /Users/0x41c/Desktop/development/WebKit/WebKitBuild/Debug/jsc
  Expected in: /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
[1]    86363 abort      ./WebkitBuild/Debug/jsc
```

**Comment by turnerrocks1** [comment]
what exactly are you building on because the latest mac os version and the latest git pull as of 03/30/22 5:50PM CST. which was an hour ag. But I don't have a clue what you mean by Revision file?

**Comment by turnerrocks1** [comment]
oops this is the correct patch i pulled the original jsc.cpp file from github took your webkit.patch manually added all the needed functions to it then saved it as jsc.cpp  then  grabbed the original jsc.cpp from github once more ranned git diff jsc.cpp *manually added patched version* jsc.cpp.orig *original non touched jsc.cpp from github* > new1.patch
[new1.patch.txt](https://github.com/googleprojectzero/fuzzilli/files/8385035/new1.patch.txt)

**Comment by turnerrocks1** [comment]
@0x41c done i pushed a pull request he has to approve it!

**Comment by turnerrocks1** [comment]
@0x41c what exactly did you change it to? and also do you have a m1 mac if so how did you get around the startup crash?

**Comment by 0x41c** [comment]
I changed it to the build folder which would usually be: `Webkit/FuzzBuild/Debug` (For whatever reason mine is within `Webkit/source/FuzzBuild`. If you're having the same issue I hope this helps.

```bash
export DYLD_FRAMEWORK_PATH=$(pwd)/FuzzBuild/Debug
```

Run this while in the parent folder of the build directory.

If the issue you're experiencing is unrelated to the one I just talked about, I sadly am unable to help as I don't currently own an M1 Mac.

**Comment by turnerrocks1** [comment]
0x41c thank you so much this fixed one of my 2 issues for m1 mac, the other issue im having is exactly this[ ](https://github.com/googleprojectzero/fuzzilli/issues/307)
I've used #define USE_PTHREAD_JIT_PERMISSIONS_API 1 
Still same error and i've tried 0 neither work but thank you!

**Comment by 0x41c** [comment]
It should be set to 1 unless on an apple-internal build of the SDK. What issue are you experiencing?

**Comment by turnerrocks1** [comment]
@0x41c this is my exact issue https://github.com/googleprojectzero/fuzzilli/issues/307

**Comment by 0x41c** [comment]
Clear the build folder and rebuild with the defined macro. That will most likely clear up the issues

**Comment by turnerrocks1** [comment]
@0x41c 
Still not working Oddly
[COV] no shared memory bitmap available, skipping
[COV] edge counters initialized. Shared memory: (null) with 819943 edges
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==12813==ERROR: UndefinedBehaviorSanitizer: BUS on unknown address (pc 0x0001a55101b8 bp 0x000100776c54 sp 0x00016f7a2cc0 T55764)
==12813==The signal is caused by a UNKNOWN memory access.
==12813==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x1a55101b8 in _platform_memmove+0xa8 (libsystem_platform.dylib:arm64e+0x41b8)

==12813==Register values:
 x[0] = 0x000000010dc04000   x[1] = 0x000000010c060280   x[2] = 0x000000000000009c   x[3] = 0x000000010dc04020  
 x[4] = 0xfffffffffe45c240   x[5] = 0x0000000000000020   x[6] = 0x00000001024d9702   x[7] = 0x0000000000000000  
 x[8] = 0x0000000158008839   x[9] = 0x0000000000000014  x[10] = 0x0000000000000004  x[11] = 0x00000000000001dc  
x[12] = 0x0000000034000000  x[13] = 0x0000000000000000  x[14] = 0x0000000000000120  x[15] = 0x0000000000000001  
x[16] = 0x00000001a5510110  x[17] = 0x00000001ffcd3ee0  x[18] = 0x0000000000000000  x[19] = 0x000000010dc040bc  
x[20] = 0x00000000000000bc  x[21] = 0x000000016f7a2f38  x[22] = 0x000000010c060240  x[23] = 0x00000000000000bc  
x[24] = 0x000000010dc04000  x[25] = 0x000000016f7a2e58  x[26] = 0x000000016f7a2f38  x[27] = 0x000000010c060280  
x[28] = 0x0000000000000040     fp = 0x000000016f7a2da0     lr = 0x0000000100776c54     sp = 0x000000016f7a2cc0  
UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: BUS (libsystem_platform.dylib:arm64e+0x41b8) in _platform_memmove+0xa8
==12813==ABORTING

**Comment by turnerrocks1** [comment]
this is the macro i defined and still doesn't work
#if (PLATFORM(MAC) && __MAC_OS_X_VERSION_MIN_REQUIRED >= 110000) \
    || (PLATFORM(MACCATALYST) && __IPHONE_OS_VERSION_MIN_REQUIRED >= 140000) \
    || (PLATFORM(IOS) && PLATFORM(IOS_FAMILY_SIMULATOR) && __IPHONE_OS_VERSION_MIN_REQUIRED >= 140000) \
    || (PLATFORM(WATCHOS) && PLATFORM(IOS_FAMILY_SIMULATOR) && __WATCH_OS_VERSION_MIN_REQUIRED >= 70000) \
    || (PLATFORM(APPLETV) && PLATFORM(IOS_FAMILY_SIMULATOR) && __TV_OS_VERSION_MIN_REQUIRED >= 140000)
/*#if USE(APPLE_INTERNAL_SDK)
/ Always use the macro on internal builds /
#define USE_PTHREAD_JIT_PERMISSIONS_API 0 
#else */
#define USE_PTHREAD_JIT_PERMISSIONS_API 1
#endif

**Comment by turnerrocks1** [comment]
@0x41c nvm it works now

**Comment by 0x41c** [comment]
Glad to see that!

**Comment by turnerrocks1** [comment]
@0x41c Basically for future reference for myself or any other person with this problem right after "pragma once" in PlatformUse.h thats when you put #define USE_PTHREAD_BLAHBLAH 1 .
