### ISSUE TITLE
Webkit [Fuzzer] Testcase "fuzzilli('FUZZILLI_CRASH', 2)" did not crash

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#338]
Just like https://github.com/googleprojectzero/fuzzilli/issues/234
[Fuzzer] Initialized
[Fuzzer] Testcase "fuzzilli('FUZZILLI_CRASH', 2)" did not crash
[Fuzzer] Shutting down due to fatal error

++++++++++ Fuzzer Finished ++++++++++

Fuzzer Statistics
-----------------
Total Samples:                0
Interesting Samples Found:    0 (nan% with runtime type information)
Valid Samples Found:          0
Corpus Size:                  0
Correctness Rate:             nan%
Timeout Rate:                 nan%
Crashes Found:                0
Timeouts Hit:                 0
Coverage:                     0.00%
Avg. program size:            0.00
Connected workers:            0
Execs / Second:               0.00
Fuzzer Overhead:              38.03%
Total Execs:                  10
Type collection timeout rate: nan%
Type collection failure rate: nan%
bootywarrior@Bootys-MacBook-Air Debug % 

bootywarrior@Bootys-MacBook-Air Webkit % /Users/bootywarrior/Webkit/FuzzBuild/Release/bin/jsc
[COV] no shared memory bitmap available, skipping
[COV] edge counters initialized. Shared memory: (null) with 819947 edges
>>> fuzzilli('FUZZILLI_CRASH',2)
undefined
>>>

**Comment by turnerrocks1** [comment]
Ideally i think it has something to do with the fact that this is release build ?

**Comment by turnerrocks1** [comment]
@saelo In JSC.cpp looking at functionFuzzilli 
The fuzzer started working once I changed it to this *which I know is incorrect commenting out the asserts* changing it to this

if (operation == "FUZZILLI_CRASH") {
        auto arg = callFrame->argument(1).toInt32(globalObject);
        RETURN_IF_EXCEPTION(scope, encodedJSValue());
        switch (arg) {
            case 0:
                *((int*)0x41414141) = 0x1337;
                break;
            case 1:
                //RELEASE_ASSERT(0);
                *((int*)0x41414141) = 0x1337;
                break;
            case 2:
                //ASSERT(0);
                *((int*)0x41414141) = 0x1337;
                break;
        }

**Comment by turnerrocks1** [comment]
Even better working solution :)

if (operation == "FUZZILLI_CRASH") {
        auto arg = callFrame->argument(1).toInt32(globalObject);
        RETURN_IF_EXCEPTION(scope, encodedJSValue());
        switch (arg) {
            case 0:
                *((int*)0x41414141) = 0x1337;
                break;
            case 1:
                RELEASE_ASSERT(0);
                *((int*)0x41414141) = 0x1337;
                break;
            case 2:
                ASSERT(0);
                *((int*)0x41414141) = 0x1337;
                break;
        }

**Comment by saelo** [comment]
Yeah, this is due to a release build. This test checks for the presence of debug assertions. I'd just remove the testcase from here: https://github.com/googleprojectzero/fuzzilli/blob/b20db8259f31feae6fbdb2dda674886b9494af0a/Sources/FuzzilliCli/Profiles/JSCProfile.swift#L64
but changing the patch works as well.
