### ISSUE TITLE
Help needed with compiling JSC with the patch

### ISSUE THREAD

**Issue by Keryer** [googleprojectzero/fuzzilli#341]
When I follow the instructions in the document，I get:
![image](https://user-images.githubusercontent.com/55967871/163663820-0b6771f9-b5f2-472f-b6a4-bc7fa3b40d40.png)

It seems that the version number given in the revision file is not a valid version number.
Any help would be very much appreciated, thanks !

**Comment by saelo** [comment]
Are you using the repo from webkit.org or from github.com? They unfortunately have different commit hashes, and [Fuzzilli is using the github](https://github.com/googleprojectzero/fuzzilli/tree/main/Targets/JavaScriptCore) one (which [seems to be recommended](https://webkit.org/getting-the-code/)): There the commit from the [REVISION file](https://github.com/googleprojectzero/fuzzilli/blob/main/Targets/JavaScriptCore/REVISION) should be valid: https://github.com/WebKit/WebKit/commit/4110e1b44a345737cdb807d36572c8714e90c5d0

**Comment by Keryer** [comment]
> 您使用的是来自 webkit.org 还是来自 github.com 的 repo？不幸的是，他们有不同的提交哈希值，[Fuzzilli 使用的是 github](https://github.com/googleprojectzero/fuzzilli/tree/main/Targets/JavaScriptCore)哈希值（这[似乎是推荐](https://webkit.org/getting-the-code/)的）：来自[REVISION 文件](https://github.com/googleprojectzero/fuzzilli/blob/main/Targets/JavaScriptCore/REVISION)的提交应该是有效的：[WebKit/WebKit@ 4110e1b](https://github.com/WebKit/WebKit/commit/4110e1b44a345737cdb807d36572c8714e90c5d0)

I have solved this problem. Thank you very much for your help
