### ISSUE TITLE
Whats this crash?

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#353]
Building for debugging...
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:48: warning: will never be executed
    guard _isDebugAssertConfiguration() else { return }
                                               ^
/home/turnerrocks1/Desktop/1/fuzzilli/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to true
    guard _isDebugAssertConfiguration() else { return }
          ^
[212/212] Linking FuzzilliCli
Build complete! (10.58s)
[Coverage] Initialized, 624850 edges
[JavaScriptEnvironment] initialized static JS environment model
[JavaScriptEnvironment] Have 60 available builtins: ["WeakSet", "EvalError", "WeakMap", "isFinite", "fiatInt52", "fullGC", "Object", "Set", "Promise", "BigInt", "Function", "Map", "Math", "undefined", "Uint32Array", "forceGCSlowPaths", "Int8Array", "JSON", "NaN", "edenGC", "runString", "noFTL", "Uint16Array", "ensureArrayStorage", "TypeError", "Int16Array", "gc", "String", "Float64Array", "placeholder", "Date", "Number", "drainMicrotasks", "Error", "Float32Array", "Infinity", "ArrayBuffer", "Symbol", "noInline", "parseInt", "RangeError", "isNaN", "Proxy", "makeMasquerader", "Array", "Boolean", "DataView", "ReferenceError", "Reflect", "createGlobalObject", "Uint8Array", "AggregateError", "Uint8ClampedArray", "Int32Array", "transferArrayBuffer", "SyntaxError", "eval", "parseFloat", "OSRExit", "RegExp"]
[JavaScriptEnvironment] Have 212 available method names: ["toString", "setFullYear", "startsWith", "raw", "subarray", "tan", "isFrozen", "allSettled", "test", "sinh", "log1p", "toLocaleString", "asIntN", "toISOString", "concat", "setUTCHours", "toLowerCase", "toDateString", "setUTCMinutes", "endsWith", "preventExtensions", "exp", "clear", "fromCharCode", "pop", "search", "fround", "getUTCMinutes", "getOwnPropertySymbols", "cos", "random", "exec", "keys", "reduceRight", "flatMap", "freeze", "then", "push", "substring", "setMilliseconds", "replaceAll", "toGMTString", "fill", "padEnd", "setUTCFullYear", "values", "getYear", "getMonth", "setFloat64", "pow", "stringify", "setUint16", "entries", "log", "sort", "isNaN", "hypot", "bind", "get", "setUTCSeconds", "every", "finally", "setUTCMonth", "max", "setDate", "keyFor", "getOwnPropertyDescriptors", "sign", "setTime", "seal", "includes", "getFloat32", "toUTCString", "of", "atan2", "isArray", "getSeconds", "setPrototypeOf", "compile", "isExtensible", "unshift", "getUTCFullYear", "setUTCDate", "shift", "expm1", "tanh", "trimRight", "atanh", "isInteger", "getTimezoneOffset", "some", "assign", "match", "deleteProperty", "charAt", "sqrt", "isSafeInteger", "localeCompare", "padStart", "isSealed", "getInt16", "isView", "cbrt", "indexOf", "reduce", "min", "getDay", "getUTCMilliseconds", "join", "log2", "from", "asin", "setInt16", "getUTCSeconds", "replace", "toJSON", "setHours", "trimLeft", "apply", "trimStart", "getUint8", "asinh", "filter", "round", "cosh", "copyWithin", "abs", "reverse", "defineProperty", "race", "setMonth", "delete", "getDate", "getUTCMonth", "getInt32", "defineProperties", "create", "setMinutes", "acosh", "n", "p", "find", "resolve", "toTimeString", "charCodeAt", "setUTCMilliseconds", "fromEntries", "getTime", "flat", "setSeconds", "catch", "call", "lastIndexOf", "set", "slice", "trunc", "getUTCDay", "map", "has", "log10", "matchAll", "ownKeys", "ceil", "add", "trim", "getUTCHours", "clz32", "setUint32", "getMinutes", "atan", "fromCodePoint", "is", "getFloat64", "toUpperCase", "getHours", "forEach", "reject", "getUint32", "parse", "getFullYear", "asUintN", "setInt32", "resize", "setUint8", "construct", "m", "codePointAt", "acos", "getPrototypeOf", "getMilliseconds", "now", "findIndex", "getInt8", "for", "splice", "o", "setInt8", "trimEnd", "getOwnPropertyDescriptor", "UTC", "all", "setYear", "sin", "imul", "split", "isFinite", "repeat", "getUint16", "setFloat32", "getUTCDate", "getOwnPropertyNames", "floor"]
[JavaScriptEnvironment] Have 51 property names that are available for read access: ["EPSILON", "dotAll", "caller", "PI", "global", "buffer", "matchAll", "toPrimitive", "MIN_SAFE_INTEGER", "iterator", "unscopable", "ignoreCase", "split", "MAX_VALUE", "d", "constructor", "search", "replace", "e", "description", "prototype", "isConcatSpreadable", "sticky", "unicode", "multiline", "hasInstance", "__proto__", "toStringTag", "b", "size", "species", "arguments", "NaN", "byteLength", "a", "flags", "c", "toString", "E", "valueOf", "asyncIterator", "MIN_VALUE", "byteOffset", "source", "message", "NEGATIVE_INFINITY", "match", "name", "MAX_SAFE_INTEGER", "length", "POSITIVE_INFINITY"]
[JavaScriptEnvironment] Have 10 property names that are available for write access: ["d", "c", "constructor", "toString", "valueOf", "length", "e", "a", "b", "__proto__"]
[JavaScriptEnvironment] Have 5 custom property names: ["e", "a", "b", "d", "c"]
[JavaScriptEnvironment] Have 4 custom method names: ["o", "p", "m", "n"]
Trace/breakpoint trap (core dumped)

**Comment by turnerrocks1** [comment]
uname -a
Linux turnerrocks1-QEMU-Virtual-Machine 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 12:56:31 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by turnerrocks1** [comment]
swift --version
Swift version 5.6.2 (swift-5.6.2-RELEASE)
Target: aarch64-unknown-linux-gnu

**Comment by saelo** [comment]
What is the command line that you are using? Can you attach a debugger and print the backtrace at the point of the crash?

**Comment by turnerrocks1** [comment]
I fixed it with a fresh install and downloading latest fuzzilli, though it still shows the logging.swift warnings on latest fuzzilli.
