### ISSUE TITLE
Debug Assertion failed at /Users/bootywarrior/Downloads/fuzzilli-main/Sources/Fuzzilli/Core/ProgramBuilder.swift:513: Unexpected type encountered .integer | .object()

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#356]
Running commands : swift run -c debug FuzzilliCli --profile=jsc --jobs=4 --consecutiveMutations=2 --engine=multi --corpus=markov --storagePath=/Users/bootywarrior/Desktop/Aggyfuzz --collectRuntimeTypes --importCorpusMerge=/Users/bootywarrior/Desktop/mergeddcorpus --overwrite /Users/bootywarrior/Downloads/Webkit/latest/WebKit/FuzzBuild/Debug/bin/jsc

Yields... 

-----------------
Fuzzer phase:                 Fuzzing (with MultiEngine)
Uptime:                       0d 0h 28m 1s
Total Samples:                19
Interesting Samples Found:    4799 (97.04% with runtime type information)
Last Interesting Sample:      0d 0h 0m 1s
Valid Samples Found:          4
Corpus Size:                  4799
Correctness Rate:             nan% (21.05%)
Timeout Rate:                 nan% (21.05%)
Crashes Found:                0
Timeouts Hit:                 4
Coverage:                     15.34%
Avg. program size:            nan
Avg. corpus program size:     35.89
Connected workers:            3
Execs / Second:               54.91
Fuzzer Overhead:              32.67%
Total Execs:                  73791
Type collection timeout rate: 5.00%
Type collection failure rate: 0.23%

[F4809D3F:Assert] Debug Assertion failed at /Users/bootywarrior/Downloads/fuzzilli-main/Sources/Fuzzilli/Core/ProgramBuilder.swift:513: Unexpected type encountered .integer | .object()

**Comment by saelo** [comment]
This is now fixed, `generateVariable()` no longer exists: https://github.com/googleprojectzero/fuzzilli/commit/e264abb403c3c63b713d20c8649f0840a59a08cd
