### ISSUE TITLE
'%' unexpected token

### ISSUE THREAD

**Issue by baptistapedro** [googleprojectzero/fuzzilli#36]
im trying to run a crash generated by fuzilli and have something like this on the code `%NeverOptimizeFunction(main)
```
SyntaxError: Unexpected token %
%NeverOptimizeFunction(main);
^
SyntaxError: Unexpected token %
```
I'm running ./d8 without any flags.

I'd appreciate if you could tell me how to avoid that error and also what flags/parameters I should use on d8 for a better crash output detail like asan.

tks

**Comment by deeku124** [comment]
how did u solve this error

**Comment by pgrace-google** [comment]
--allow-natives-syntax flag fixes it for me
