### ISSUE TITLE
Debug Assertion failed at .... AbstractInterpreter.swift:207

### ISSUE THREAD

**Issue by shreyashs06** [googleprojectzero/fuzzilli#360]
Trying to run the fuzzer on QuickJS, using command :
`swift run FuzzilliCli --profile=qjs --storagePath=./output ../quickjs/qjs`

Running into an error:

```
[Assert] Debug Assertion failed at /Users/shreyashs/Desktop/fuzz_quickjs/fuzzilli/Sources/Fuzzilli/FuzzIL/AbstractInterpreter.swift:207
[Fuzzer] Shutting down due to fatal error

++++++++++ Fuzzer Finished ++++++++++

Fuzzer Statistics
-----------------
Fuzzer phase:                 Initial corpus generation (with GenerativeEngine)
Uptime:                       0d 0h 1m 4s
Total Samples:                3437
Interesting Samples Found:    489
Last Interesting Sample:      0d 0h 0m 0s
Valid Samples Found:          1563
Corpus Size:                  489
Correctness Rate:             46.80% (45.48%)
Timeout Rate:                 0.20% (0.41%)
Crashes Found:                0
Timeouts Hit:                 14
Coverage:                     17.21%
Avg. program size:            13.69
Avg. corpus program size:     6.22
Connected workers:            0
Execs / Second:               225.25
Fuzzer Overhead:              86.00%
Total Execs:                  13109
```

Can anyone help with this please?

**Comment by turnerrocks1** [comment]
did you change any of the fuzzilli code? I rained into this planty of times to try to help the fuzzer find "unfound bugs" either you changed something incorrectly or... Same error I just faced 3 days ago as you it happens when compiled with swift run -c debug... instead use swift run -c release to stop this from happening.

**Comment by saelo** [comment]
Thanks for the report! Should be fixed now with https://github.com/googleprojectzero/fuzzilli/commit/4da029f6d00a78b77825b10e522db2f252f7e52b
