### ISSUE TITLE
Possible Coverage Maxiumum?

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#361]
This would fall under the question label but I've been curious without fuzzying wasm which fuzzilli doesn't natively support how much coverage percentage is possible to reach? What is the fuzzer coverage represent does it represents code coverage as whole in JavaScriptCore if so then could one infer that the fuzzer can never truly reach 100%, Only asking out of curiosity because I notice around the 17%-20% mark the coverage increase starts to slow drastically almost to a standstill for hours *even though exec/second is still in the high hundreds* this was observed around reaching the 10M exec mark with fuzzilli also let's say 100% is reached would fuzzilli stop the session or something if it reaches 100%?

**Comment by saelo** [comment]
Yeah, Fuzzilli will usually only reach ~25% or so on current JSC builds, for V8 it's even less (and coverage increase drops sharply after a few hours, as you've noted). There's a ton of code that cannot be reached during Fuzzing, also there are many conditions (such as all the assertions) that will normally always branch in one direction (so only get 50% covered). If you're curious where coverage is missing, you could generate and inspect source coverage reports from a Fuzzilli corpus: https://clang.llvm.org/docs/SourceBasedCodeCoverage.html
Fuzzilli doesn't stop fuzzing unless you've specified a --numIterations value.

**Comment by turnerrocks1** [comment]
@saelo Thanks that was a perfectly explained answer and exactly what I was wondering :).
