### ISSUE TITLE
Handle openFile better?

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#362]
After a while fuzzilli will start implementing using the openFile Method. And generate code such as this 
*"const v318 = v316["openFile"]();"*. Running such code by itself will result in URI Error for some reason, The end results of such test cases results in "flakey" false positive crashes for some odd reason I have multiple instances of this happening for some reason.

**Comment by turnerrocks1** [comment]
Another follow up with more details with "--logJIT=true" generates this : 
"Exception: URIError: Could not open file at file:///undefined fopen had error: Too many open files
openFile@[native code]".

**Comment by saelo** [comment]
Which JS engine is this happening with? I think the best thing to deal with this would be to disable any JS-exposed APIs that may cause unintended side-effects, such as file system access or shell command executions, similar to what `--fuzzing` does in V8 (see e.g. https://source.chromium.org/chromium/chromium/src/+/main:v8/src/d8/d8.cc;l=3200;drc=d855d7f7b18905748772d10a4a569366e240e120)

**Comment by turnerrocks1** [comment]
JSC engine. And ok then Thanks.
