### ISSUE TITLE
Warning during swift run

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#365]
Don't know if this is useful to you or not but this warning is generated during compilation.

remark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with who/Users/bootywarrior/Desktop/fuzzilli-main/Sources/Fuzzilli/Core/Logging.swift:33:9: warning: will never be executed
    if !condition() {
        ^
/Users/bootywarrior/Desktop/fuzzilli-main/Sources/Fuzzilli/Core/Logging.swift:31:11: note: condition always evaluates to false
    guard _isDebugAssertConfiguration() else { return }
          ^
remark: Incremental compilation has been disabled: it is not compatible with who[10/10] Linking FuzzilliCli

**Comment by saelo** [comment]
Yeah these are unfortunately now there because we have our own version of `Assert` that forwards errors to master nodes. Apparently it's not possible to suppress these warnings...
