### ISSUE TITLE
Future update for Temporal in JSC

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#366]
https://github.com/WebKit/WebKit/commit/e6717cdeb6a841f4b1f6b9d8d3b0dec947850abe

**Comment by saelo** [comment]
Thanks to the new [ExplorationMutator](https://github.com/googleprojectzero/fuzzilli/blob/main/Sources/Fuzzilli/Mutators/ExplorationMutator.swift) we don't necessarily need to add these APIs to the JSEnvironment model, the mutator will also find them. If we then realize that these APIs are interesting for fuzzing, we can still add it to the environment later on.
