### ISSUE TITLE
fuzzying v8 error

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#369]
error listed shortly after start "[Fuzzer] Cannot execute programs (exit code must be zero when no exception was thrown). Are the command line flags valid?"
Shortly after finding out that v8 won't build on macOS with trace pc guard I downloaded v8 and installed ubuntu and built using the following command listed in fuzzbuild.sh
Ubuntu 20.04.5 gives 

turner@turner-Standard-PC-Q35-ICH9-2009:~/Desktop/fuzzilli-main/fuzzilli-main$ swift run -c release FuzzilliCli --profile=v8 --storagePath=/home/turner/Desktop/v8fuzz --resume /home/turner/Desktop/v8/v8/out/fuzzbuild/d8 
Building for production...
Build complete! (2.07s)
[Coverage] Initialized, 845304 edges
[JavaScriptEnvironment] initialized static JS environment model
[JavaScriptEnvironment] Have 55 available builtins: ["String", "DataView", "Error", "EvalError", "OptimizeFunctionOnNextCall", "Object", "DeoptimizeFunction", "isNaN", "TypeError", "ArrayBuffer", "RangeError", "RegExp", "Uint8Array", "Int8Array", "Number", "Date", "OptimizeOsr", "Boolean", "Math", "Array", "URIError", "Int16Array", "Reflect", "NaN", "Float32Array", "isFinite", "Uint8ClampedArray", "Infinity", "DeoptimizeNow", "Map", "Set", "Float64Array", "WeakSet", "parseFloat", "ReferenceError", "Proxy", "eval", "BigInt", "JSON", "parseInt", "Int32Array", "Function", "gc", "Symbol", "undefined", "placeholder", "NeverOptimizeFunction", "SyntaxError", "AggregateError", "Uint16Array", "PrepareFunctionForOptimization", "print", "Uint32Array", "Promise", "WeakMap"]
[JavaScriptEnvironment] Have 212 available method names: ["setUint32", "min", "setPrototypeOf", "assign", "replace", "includes", "getOwnPropertyDescriptor", "cos", "keyFor", "fromCodePoint", "getTime", "getMilliseconds", "padEnd", "atan2", "max", "matchAll", "then", "getFullYear", "splice", "getSeconds", "resolve", "keys", "parse", "getUint8", "UTC", "for", "find", "setYear", "set", "getUTCDay", "shift", "every", "trimStart", "concat", "setInt16", "defineProperties", "cbrt", "unshift", "setMonth", "setUint16", "match", "imul", "isNaN", "log2", "search", "trim", "toLocaleString", "isExtensible", "setUTCFullYear", "apply", "setMinutes", "setInt8", "getOwnPropertyNames", "sinh", "codePointAt", "isSafeInteger", "reverse", "getDate", "getUint32", "log1p", "localeCompare", "setFullYear", "resize", "sin", "reduce", "fill", "push", "getYear", "from", "toTimeString", "trimRight", "split", "log10", "setDate", "raw", "defineProperty", "getFloat64", "forEach", "setUTCMinutes", "now", "fromEntries", "entries", "join", "isArray", "findIndex", "flat", "clz32", "random", "getUTCHours", "setFloat32", "floor", "get", "ceil", "filter", "p", "deleteProperty", "reject", "charAt", "setTime", "isInteger", "m", "getUint16", "sqrt", "round", "of", "call", "getTimezoneOffset", "fround", "construct", "allSettled", "setUTCMonth", "acosh", "create", "acos", "getInt8", "toLowerCase", "n", "race", "trimEnd", "some", "lastIndexOf", "replaceAll", "cosh", "subarray", "is", "exec", "isFrozen", "slice", "asUintN", "getOwnPropertyDescriptors", "setUTCMilliseconds", "tanh", "toUpperCase", "asinh", "stringify", "charCodeAt", "repeat", "o", "copyWithin", "trimLeft", "compile", "freeze", "pop", "ownKeys", "setFloat64", "toGMTString", "getPrototypeOf", "asin", "asIntN", "all", "setUTCHours", "isSealed", "getOwnPropertySymbols", "indexOf", "tan", "setUTCSeconds", "hypot", "expm1", "setUTCDate", "delete", "log", "setUint8", "map", "getUTCMonth", "reduceRight", "toDateString", "toString", "clear", "trunc", "setSeconds", "values", "test", "getMonth", "add", "startsWith", "getInt16", "getUTCDate", "padStart", "pow", "sign", "fromCharCode", "has", "getUTCFullYear", "toJSON", "isFinite", "getFloat32", "isView", "sort", "exp", "atan", "toUTCString", "preventExtensions", "abs", "seal", "getHours", "setHours", "getInt32", "getDay", "getUTCSeconds", "substring", "endsWith", "catch", "bind", "getMinutes", "toISOString", "atanh", "setMilliseconds", "getUTCMilliseconds", "getUTCMinutes", "finally", "flatMap", "setInt32"]
[JavaScriptEnvironment] Have 52 property names that are available for read access: ["toPrimitive", "PI", "length", "unscopables", "toString", "replace", "valueOf", "source", "NaN", "message", "arguments", "E", "name", "multiline", "MAX_VALUE", "unicode", "prototype", "search", "buffer", "a", "b", "toStringTag", "NEGATIVE_INFINITY", "byteLength", "iterator", "MAX_SAFE_INTEGER", "description", "c", "POSITIVE_INFINITY", "MIN_SAFE_INTEGER", "caller", "sticky", "MIN_VALUE", "constructor", "flags", "EPSILON", "species", "e", "ignoreCase", "matchAll", "global", "isConcatSpreadable", "__proto__", "asyncIterator", "dotAll", "split", "cause", "d", "match", "hasInstance", "size", "byteOffset"]
[JavaScriptEnvironment] Have 10 property names that are available for write access: ["constructor", "b", "e", "length", "c", "toString", "a", "d", "valueOf", "__proto__"]
[JavaScriptEnvironment] Have 5 custom property names: ["e", "a", "b", "d", "c"]
[JavaScriptEnvironment] Have 4 custom method names: ["m", "p", "n", "o"]
[Fuzzer] Initialized
[Fuzzer] Cannot execute programs (exit code must be zero when no exception was thrown). Are the command line flags valid?
[Fuzzer] Shutting down due to fatal error

++++++++++ Fuzzer Finished ++++++++++

Fuzzer Statistics
-----------------
Fuzzer phase:                 Fuzzing (with MultiEngine)
Uptime:                       0d 0h 0m 1s
Total Samples:                0
Interesting Samples Found:    0
Last Interesting Sample:      0d 0h 0m 1s
Valid Samples Found:          0
Corpus Size:                  0
Correctness Rate:             -nan% (-nan%)
Timeout Rate:                 -nan% (-nan%)
Crashes Found:                0
Timeouts Hit:                 0
Coverage:                     0.00%
Avg. program size:            -nan
Avg. corpus program size:     -nan
Connected workers:            0
Execs / Second:               0.00
Fuzzer Overhead:              85.18%
Total Execs:                  1

**Comment by turnerrocks1** [comment]
Seem to be crashing on this line,
Weirdly MacOS 12.5 swift 5.6.0 runs fuzzilli just fine
But Ubuntu 20.04.5 LTS swift 5.7.0 I'm having problems

https://github.com/googleprojectzero/fuzzilli/blob/7ac136b3ba6fccae03fe754425c7f475fcbb64c4/Sources/Fuzzilli/Fuzzer.swift#L750

**Comment by saelo** [comment]
Locally I'm not running into this issue. What version of V8 are you using? If it's an old version, then maybe `Are the command line flags valid?` is the issue. You could also try adding something like `print(execution.stderr)` before that `fatal` message to see if that gives any hints. Or you could try `swift run REPRLRun /home/turner/Desktop/v8/v8/out/fuzzbuild/d8` and pass it the flags from https://github.com/googleprojectzero/fuzzilli/blob/main/Sources/FuzzilliCli/Profiles/V8Profile.swift#L204 to see what's going on

**Comment by turnerrocks1** [comment]
@saelo was missing --jobs= arg but I'm glad it didn't work at first because now I was able to find and use an actual non buggy arm64 ubuntu image :),  now it's working properly thanks.
