### ISSUE TITLE
false positives crashes?

### ISSUE THREAD

**Issue by baptistapedro** [googleprojectzero/fuzzilli#37]
I have some crashes files generated by fuzzilli but when I run on d8 with --allow-natives-syntax
most of them doesn't crash d8 or show any error... That's happening to most of the files. Are those false positives or I'm missing something?

**Comment by baptistapedro** [comment]
and there are other files that I assume are infinite loops? Does it count as crash for the fuzzer?

**Comment by saelo** [comment]
Are you reproing them with all commandline flags that fuzzilli uses: https://github.com/googleprojectzero/fuzzilli/blob/2e7c967d171a5059aff6f9ab8df6be0e36216018/Sources/FuzzilliCli/Profiles/V8Profile.swift#L30?

**Comment by baptistapedro** [comment]
I'm using all those commandline flags with the execption of --reprl (even tho I applied the patch it isnt recognized).

But even with all those flags the output is the same.

I tried to run the script on asan-chromium and the tab definitely crashes but there isn't any asan log.
The only thing shown is this `[14764:15052:0725/171438.572:ERROR:browser_process_sub_thread.cc(221)] Waited 94 ms for network service`

which I believe isn't a major thing? :/

**Comment by baptistapedro** [comment]
yeah i guess are just inf loops

**Comment by saelo** [comment]
Hmm that's weird, timeouts shouldn't be treated as crashes. What is the termination signal of the crashes? You can find that in the filename of the crashes, they are structured like this: crash_$timestamp_$pid_[deterministic/flaky]_**$signal**.js.
Are you trying to reproduce the crashes on the same machine with the same d8 build that you are also using for fuzzing? Maybe they somehow end up causing OOM crashes due to resource limitations or smth like that...

**Comment by baptistapedro** [comment]
All of the files have the termination signal 4 (SIGILL) if I'm not wrong. 
Can those be considered security flaws?

Yes I'm trying to reproduce the crashes on the same machine where the fuzzer is running.

**Comment by saelo** [comment]
SIGILL usually means an assertion fail (CHECK or DCHECK). Maybe one thing you can try is displaying stderr of the child processes and see if you get the "Check failed" messages printed. For that either just uncomment this line: https://github.com/googleprojectzero/fuzzilli/blob/2e7c967d171a5059aff6f9ab8df6be0e36216018/Sources/libreprl/libreprl.c#L106 or instead set stderr to some other file descriptor for a log file or so

**Comment by baptistapedro** [comment]
It is uncomment by default, I assume you meant to comment it.  I've tried either way and I get the same  behaviour :/

When you mean set stderr to some other file descriptor and log it I assume it's like
```./d8 --debug-code --expose-gc --single-threaded --predictable --allow-natives-syntax --interrupt-budget=1024 --no-arguments c/8.js > log8.txt
```

I've tried that and the log file is empty because the d8 will run inside a loop.

I sent you a crash file so you can also do some debug. Check your inbox pls.
