### ISSUE TITLE
macOS use build-jsc without --jsc-only

### ISSUE THREAD

**Issue by turnerrocks1** [googleprojectzero/fuzzilli#372]
As the bug report on : https://bugs.webkit.org/show_bug.cgi?id=245295 that I published.

I've been having problems recently compiling --jsc-only ports on macOS within these last 2 months.

As --jsc-only is meant for macOS nor is the static build neither so any slight change in a commit can break building in the future.

Another prime example of a bug report of mines for a broken build was this : https://bugs.webkit.org/show_bug.cgi?id=244751.

Just a recommendation that I'm just passing on.

**Comment by turnerrocks1** [comment]
@saelo hey I was instructed to ask you per : https://bugs.chromium.org/p/chromium/issues/detail?id=1364141#c13

What would be needed to add fuzzilli support to v8 for for Mac support in regards to the "trace-pc-gaurd" flag.

**Comment by turnerrocks1** [comment]
also this @saelo : https://bugs.chromium.org/p/chromium/issues/detail?id=1364141#c11

**Comment by saelo** [comment]
Thanks for investigating! Yeah the macOS builds are essentially all unsupported, so we should just remove them from the build files: https://github.com/googleprojectzero/fuzzilli/commit/9919ae50fa3f8820df575fa498e8e2881f538da7 Linux is anyway better for fuzzing, macOS only maybe makes sense for local development. But if you can figure out a supported way of getting static binaries with sanitizer coverage (the trace-pc-guard stuff) on macOS definitely feel free to open a PR!
