### ISSUE TITLE
Something wrong while fuzzing v8 engine

### ISSUE THREAD

**Issue by Vincebye** [googleprojectzero/fuzzilli#375]
![image](https://user-images.githubusercontent.com/19506728/191670553-99845bbb-2b88-44e2-85cb-1432dc3f5e60.png)

Building for debugging...
Build complete! (0.06s)
[REPRL] Script execution failed: Did not receive HELO message from child: Bad file descriptor. Retrying in 1 second...
[REPRL] Script execution failed again: Did not receive HELO message from child: Bad file descriptor. Giving up
[LibCoverage] Coverage bitmap size could not be determined, is the engine instrumentation working properly?

**Comment by saelo** [comment]
Did you build V8 as described here: https://github.com/googleprojectzero/fuzzilli/tree/main/Targets/V8? This error usually means the target engine wasn't compiled with Fuzzilli support.

**Comment by Vincebye** [comment]
Yes, I follow the  https://github.com/googleprojectzero/fuzzilli/tree/main/Targets/V8.

**Comment by saelo** [comment]
Hm odd, can you post the output of just running `/home/v/v8/out/fuzzbuild/d8`?

**Comment by Vincebye** [comment]
![image](https://user-images.githubusercontent.com/19506728/191975745-9c73f427-1cb0-4544-96ac-9fca754b7967.png)

**Comment by saelo** [comment]
Ok thanks, then that build is indeed missing Fuzzilli instrumentation, otherwise it'd print something like this
```
[COV] no shared memory bitmap available, skipping
[COV] edge counters initialized. Shared memory: (null) with 847984 edges
[COV] Additional 0 edges for builtins initialized.
V8 version 10.8.0 (candidate)
d8> 
```
Also it looks like a very old version to me (current version is 10.8)?

**Comment by Vincebye** [comment]
Sorry, I often have this kind of weird problem, I updated the project and it worked, thanks for your guidance
