### ISSUE TITLE
fatal error when compiling JavascriptCore using webkit.patch on ubuntu 16.04

### ISSUE THREAD

**Issue by JiounDai** [googleprojectzero/fuzzilli#38]
call void @__sanitizer_cov_trace_pc_guard(i32* inttoptr (i64 add (i64 ptrtoint ([37 x i32]* @__sancov_gen_.1200 to i64), i64 108) to i32*))
inlinable function call in a function with debug info must have a !dbg location
  call void @__sanitizer_cov_trace_pc_guard(i32* inttoptr (i64 add (i64 ptrtoint ([3 x i32]* @__sancov_gen_.1205 to i64), i64 8) to i32*))
fatal error: error in backend: Broken module found, compilation aborted!
clang-6.0: error: clang frontend command failed with exit code 70 (use -v to see invocation)

**Comment by saelo** [comment]
Hmm I think I've seen this problem before... maybe try a different clang version. I'm using clang-7 on ubuntu 18.04, but I think clang-4 should also work

**Comment by JiounDai** [comment]
I tried clang-7 on ubuntu 16.04, but failed again.  The same error.

**Comment by JiounDai** [comment]
clang-4 also not works.

**Comment by saelo** [comment]
I just confirmed that it works fine with clang-7 on 18.04. The Dockerfile is basically

```FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL=bash

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y git cmake clang-7 ruby libicu-dev

RUN useradd -m builder

USER builder
WORKDIR /home/builder

RUN git clone https://github.com/WebKit/webkit.git
ADD --chown=builder:builder webkit.patch webkit/webkit.patch
ADD --chown=builder:builder fuzzbuild.sh webkit/fuzzbuild.sh

WORKDIR /home/builder/webkit
RUN patch -p1 < webkit.patch
RUN ./fuzzbuild.sh```

My guess is that clang is somehow confused about the `__sanitizer_cov` functions. One thing you can try is moving those 3 functions to a separate .cpp like the v8 patch does. That way clang might stop trying to inline them...

**Comment by saelo** [comment]
Cool, no problem!
