### ISSUE TITLE
Uncaught ReferenceError: d8 is not defined

### ISSUE THREAD

**Issue by Miracle-doctor** [googleprojectzero/fuzzilli#381]
Uncaught ReferenceError: d8 is not defined. How can I use crashed js in real chrome browser.

**Comment by saelo** [comment]
The `d8` builtin provides a bunch of functions that are not part of the core JavaScript runtime environment. Some of them emulate features available in Chrome (e.g. the `serializer` emulates the structured clone algorithm). You'll have to figure out which feature is used and how that can be reached in Chrome.
