### ISSUE TITLE
assert fails for recursive generator with two calls to buildRecursive

### ISSUE THREAD

**Issue by phoddie** [googleprojectzero/fuzzilli#382]
The `CompartmentGenerator` for XS (in my branch) creates several function callbacks. This has worked reliably until last week's changes to Fuzzilli. The problem can be reproduced with the following generator:

```swift
fileprivate let ExampleGenerator = RecursiveCodeGenerator("ExampleGenerator") { b in
	let code = b.buildCodeString() {
		b.buildRecursive()
	}
	let resolveHook = b.buildPlainFunction(with: .parameters(n: 2)) { _ in
		b.buildRecursive()
	}
}
```

The error is `Fuzzilli/ProgramBuilder.swift:1044: Assertion failed` from this line:

```swift
assert(parentState.nextRecursiveBlockOfCurrentGenerator == block)
```

**Comment by phoddie** [comment]
Yes, it does. I guess I shouldn't have overlooked those mysterious new parameters. ;) Thank you!

**Comment by saelo** [comment]
No problem! Yeah in retrospect I maybe should've renamed the method or something like that so you'd get compile-time errors instead of runtime crashes, oh well... :)
