### ISSUE TITLE
fuzz IL compiler another no bad choice 

### ISSUE THREAD

**Issue by areuu** [googleprojectzero/fuzzilli#383]
I updated some code to adopt the latest fuzzilli 

http://github.com/areuu/ilcompiler
using ocaml 4.14.0, flow_parser 0.192.0

**Comment by saelo** [comment]
Thanks for that! There is now also a different, supported compiler in Fuzzilli: https://github.com/googleprojectzero/fuzzilli/commit/807625f0112df22bfe293aa4d36d67c31c4fb243 which should be easy to extend
