### ISSUE TITLE
Setting flags for js shell

### ISSUE THREAD

**Issue by baptistapedro** [googleprojectzero/fuzzilli#393]
Hi, what is the proper way to set runtime flags on d8?
I tried this:
```
swift run -c release FuzzilliCli --profile=v8 --storagePath=./crashes2/ --timeout=300 /home/nasa/v8/v8/out/x64_release/d8 --allow-natives-syntax
Building for production...
Build complete! (0.29s)
Invalid arguments: ["allow-natives-syntax"]```

**Comment by saelo** [comment]
Hi! You can either add these flags to the engine profile (in this case, [V8Profile.swift](https://github.com/googleprojectzero/fuzzilli/blob/main/Sources/FuzzilliCli/Profiles/V8Profile.swift)), or specify them through [--additionalArguments](https://github.com/googleprojectzero/fuzzilli/blob/main/Sources/FuzzilliCli/main.swift#L97).
