### ISSUE TITLE
--importCorpus Option Error

### ISSUE THREAD

**Issue by BruteKoon** [googleprojectzero/fuzzilli#394]
HI

The basic jsc fuzzing command works fine.
(swift run FuzzilliCli --profile=jsc /Users/user/Fuzz/WebKit-releases-Apple-Safari-16.4-macOS-13.3/FuzzBuild/Debug/bin/jsc)

but, If I add the following option statement to use the importCorpus option... an error occurs.
```
--importCorpus=/Users/user/Fuzz/fuzzilli/test

* In the folder "test", there is basic_variable.fzil where I compiled the sample code (basic_variables.js) using FuzzILTool.
``` 

The contents of the error are as follows.
(It doesn't seem to recognize it in the importPrograms function. What additional commands should I use?)
```
...
[Fuzzer] Corpus import finished:
[Fuzzer] 0/1 programs executed successfully during import
[Fuzzer] 0/1 programs timed out during import
[Fuzzer] 1/1 programs failed to execute during import ---------------> Fail....
[Fuzzer] Corpus now contains 0 programs
[Fuzzer] Changing state from corpusImport to fuzzing
Swift/Integers.swift:2665: Fatal error: Can't get random value with an empty range
```

**Comment by fr3ns1s** [comment]
@BruteKoon i have the same problem ? have you resolved it ?
