### ISSUE TITLE
Unhandled node type Super

### ISSUE THREAD

**Issue by bb33bb** [googleprojectzero/fuzzilli#400]
node parser.js ../../Protobuf/ast.proto code.js output.ast.proto

content of code.js is
// Copyright 2020 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Flags: --allow-natives-syntax --no-use-ic --super-ic

class A {
  bar() { }
}
class B extends A {
  foo() {
    return super.bar();
  }
}
%PrepareFunctionForOptimization(B.prototype.foo);
new B().foo();
%OptimizeFunctionOnNextCall(B.prototype.foo);
new B().foo();

**Comment by saelo** [comment]
Thanks, yes, these are not yet supported by our compiler, but we're happy to take PRs! See https://github.com/googleprojectzero/fuzzilli/issues/399#issuecomment-1564012050 for some general guidance on how to extend the compiler, and don't hesitate to ask for more specific guidance!

**Comment by nth10sd** [comment]
@saelo With the current work on the compiler, does this warrant a reopening? Or a new issue?

**Comment by saelo** [comment]
As the compiler isn't feature complete, there's probably not too much value in having individual issues open for every feature that's not supported. Instead, the focus should be on whatever feature is currently blocking the most testcases from being compilable, which can be determined by the script linked in issue #437.
