### ISSUE TITLE
What is the purpose of the evaluator_state.bin file?

### ISSUE THREAD

**Issue by chennbnbnb** [googleprojectzero/fuzzilli#409]
I notice that: when I enable "--exportStatistics", many "*_evaluator_state.bin" file will be generated in folder. those files take of a lot of disk space.
what does "*_evaluator_state.bin" file use for? I can't find any document about it

**Comment by carl-smith** [comment]
The evaluator_state is the state of the ProgramEvaluator, if you are using regular edge coverage, this is the state exported here: https://github.com/googleprojectzero/fuzzilli/blob/172778a3397774a337edee803fb372a48b99f5bd/Sources/Fuzzilli/Evaluation/ProgramCoverageEvaluator.swift#L243
Specifically this is the bitmap and the number of found edges. This would allow you to track the evolution of the bitmap throughout the fuzzing run.
