### ISSUE TITLE
flaky crashes false positive

### ISSUE THREAD

**Issue by AliredDevils** [googleprojectzero/fuzzilli#41]
1.Test Environment
V8 version: 7.8.0
Ubuntu 16.04
Timeout config: 380ms

2.Issues
I find some crashes files generated by fuzzilli, when I want to reproduce the crashes by running d8, but most of them doesn't crash d8 or any errors.(I use the same machine and d8 tool to reproduce the crash.)

- Command line as bellow:

        v8/out/fuzzbuild/d8 --debug-code --expose-gc --single-threaded --predictable --allow-natives-syntax --interrupt-budget=1024 --no-arguments crash_1566514916227_18444_flaky_4.js

- Results:

    [COV] no shared memory bitmap available, skipping
    [COV] edge counters initialized. Shared memory: (null) with 565526 edges

- Test shows:

    
-----------------
Total Samples:                4996990
Interesting Samples Found:    8601
Valid Samples Found:          2874108
Corpus Size:                  1032
Success Rate:                 57.52%
Timeout Rate:                 2.76%
Crashes Found:                8
Timeouts Hit:                 137813
Coverage:                     17.26%
Avg. program size:            93.80
Connected workers:            0
Execs / Second:               18.27
Total Execs:                  5768202

    

-----------------
3.Questions
Whether the flaky crashes are false positive?Please check the flaky crashes in the attachment.

**Comment by AliredDevils** [comment]
[flaky_crashes.zip](https://github.com/googleprojectzero/fuzzilli/files/3532615/flaky_crashes.zip)

**Comment by saelo** [comment]
I'm now tracking attempts to improve handling of non-reproducible crashes here: https://github.com/googleprojectzero/fuzzilli/issues/42 Feel free to try some of the things I noted there to hopefully get an idea of what is happening
