### ISSUE TITLE
pls add support class computed method and static method

### ISSUE THREAD

**Issue by areuu** [googleprojectzero/fuzzilli#421]
example
```
class A {
 ['fuck']() {}
static laji() {}
}
```
il op only have `Begin/EndClassInstanceMethod`

**Comment by saelo** [comment]
Hi! Static class methods are supported, see `BeginClassStaticMethod` but computed class methods are not implemented currently. It's not a priority for us, but we're very happy to take PRs! It's probably not too hard to implement, maybe take a look at `BeginObjectLiteralComputedMethod` for an example of a similar instruction.

**Comment by areuu** [comment]
get it, thanks.
