### ISSUE TITLE
[REPRL] Failed to communicate with child process

### ISSUE THREAD

**Issue by shuidixu** [googleprojectzero/fuzzilli#43]
Sorry for the burden, I fixed the previous issue, 
The Child Process for some reason now does not talk to the Father Process.

```
[REPRL] Failed to communicate with child process
```

-----
I saw that you added new features and I want to test them but it seems this test fails.

Edit: 
I'm trying to fix it on my own by reading your patch.

It seems that the internal fuzzilli function was not built into jsc itself although I've applied your patch.

**Comment by shuidixu** [comment]
Ok, I fixed it.
Sorry Sir for being such a noob, i only learn for educational reasons!

**Comment by hhroot** [comment]
I have the same problem, how do you solve it
