### ISSUE TITLE
Issues when trying to run Fuzzilli on CentOS

### ISSUE THREAD

**Issue by mixianghang** [googleprojectzero/fuzzilli#44]
I'm trying to get fuzzili running on a CentOS machine but I'm running into issues due to the usage of Swift. Are there any recommendations for how I can get this running?

**Comment by saelo** [comment]
If swift isn't available in the distro repositories you'll either have to compile it yourself or switch to Ubuntu, e.g. by building inside of a Docker container (that's what I do).

**Comment by saelo** [comment]
Closing this now as Docker support has landed in the meantime, which should make this easier: https://github.com/googleprojectzero/fuzzilli/tree/master/Cloud/Docker
