### ISSUE TITLE
Script size for transfer via REPRL interface is calculated based on character count and not the actual size in bytes

### ISSUE THREAD

**Issue by nbars** [googleprojectzero/fuzzilli#443]
I have noticed that test cases containing UTF-8 characters, which require more than one byte for encoding, fail to execute. The issue seems to stem from how the length of the script being transferred to the JavaScript shell is calculated.

Currently, the script length is determined by counting the number of characters (using `code.count`): https://github.com/googleprojectzero/fuzzilli/blob/aeed429d56bd771ffa5a315f57f3413fa4732b55/Sources/REPRLRun/main.swift#L49

However, when the script is copied, `memcpy` is used: https://github.com/googleprojectzero/fuzzilli/blob/aeed429d56bd771ffa5a315f57f3413fa4732b55/Sources/libreprl/libreprl-posix.c#L435

Since `memcpy` operates at the byte level, scripts containing non-ASCII characters (which may occupy more than one byte per character) are likely to be transferred only partially.

**Comment by saelo** [comment]
Ah yes, that's not great... I'll prepare a fix. Thanks for the report!
