### ISSUE TITLE
I can't run fuzzilli when import create a tmpfs

### ISSUE THREAD

**Issue by brookate** [googleprojectzero/fuzzilli#444]
this commit https://github.com/googleprojectzero/fuzzilli/commit/ed1d68b392eb7e0e9cf18482aa279fda99dd629a

my env is docker, and I can't run fuzzilli now. 
is there any other way to resolve it? I revert that commit currently.

**Comment by carl-smith** [comment]
Hi!
Thanks for filing the issue and sorry for breaking your setup.
I reverted the relevant commits, they also did not really work for us! :)
