### ISSUE TITLE
Fuzzilli crashes when passing --minimizationLimit

### ISSUE THREAD

**Issue by tobiassoppa** [googleprojectzero/fuzzilli#448]
Hey, while playing around and trying to make the minimizer less aggressive (to _increase_ the avg. code size over time), I noticed that Fuzzilli crashes shortly after starting (3-4 minutes max) when passed `--minimizationLimit`.

Steps to reproduce
```bash
# Current HEAD as of writing this issue.
git switch fb79747

# Could not reliably reproduce it in 3-4 minutes with a smaller --jobs count.
swift run FuzzilliCli --profile=v8 --minMutationsPerSample=200 --minimizationLimit=0.25 --jobs=4 path/to/d8
```

Which will output after a while
```
Fuzzer Statistics
-----------------
Fuzzer state:                 Initial corpus generation (with GenerativeEngine)
Uptime:                       0d 0h 4m 0s
Total Samples:                662
Interesting Samples Found:    312
Last Interesting Sample:      0d 0h 0m 1s
Valid Samples Found:          496
Corpus Size:                  312 (global average: 204)
Correctness Rate:             47.47% (overall: 74.92%)
Timeout Rate:                 0.72% (overall: 0.60%)
Crashes Found:                0
Timeouts Hit:                 4
Coverage:                     5.70%
Avg. program size:            44.21
Avg. corpus program size:     18.64
Avg. program execution time:  9ms
Connected nodes:              2
Execs / Second:               119.58
Fuzzer Overhead:              9.81%
Minimization Overhead:        54.18%
Total Execs:                  18670

Fuzzilli/Minimizer.swift:103: Assertion failed

💣 Program crashed: Illegal instruction at 0x00007fdb182f36b0

Thread 8 crashed:

0 0x00007fdb182f36b0 _assertionFailure(_:_:file:line:flags:) + 496 in libswiftCore.so
1 Minimizer.internalMinimize(_:withAspects:limit:runningSynchronously:) + 2701 in FuzzilliCli at /home/tobias/fuzzilli_build_test/fuzzilli/Sources/Fuzzilli/Minimization/Minimizer.swift:103:9

   101│         // Most reducers replace instructions with NOPs instead of deleting them. Remove those NOPs now.
   102│         helper.removeNops()
   103│         assert(helper.code.countIntructionsWith(flags: .notRemovable) >= helper.numKeptInstructions)
      │         ▲
   104│
   105│         // Post-process the sample after minimization. This step adds certain features back to the program that may have been minimized away but are typically helpful for future mutations.

2 closure #1 in Minimizer.withMinimizedCopy(_:withAspects:limit:block:) + 189 in FuzzilliCli at /home/tobias/fuzzilli_build_test/fuzzilli/Sources/Fuzzilli/Minimization/Minimizer.swift:47:38

    45│     func withMinimizedCopy(_ program: Program, withAspects aspects: ProgramAspects, limit minimizationLimit: Double = 0.0, block: @escaping (Program) -> ()) {
    46│         minimizationQueue.async {
    47│             let minimizedCode = self.internalMinimize(program, withAspects: aspects, limit: minimizationLimit, runningSynchronously: false)
      │                                      ▲
    48│             self.fuzzer.async {
    49│                 let minimizedProgram: Program

```

I checked a bit and saw that the failing assert has been added fairly recently (last month) in commit https://github.com/googleprojectzero/fuzzilli/commit/872e468 . I also tried to figure out _why_ it is failing and issue a PR, but so far did not spot the issue.

My assumption is that somewhere inside `helper.removeNops()`, as the same assert is also present in line `74` and line `90` and holds each time, but fails after calling `helper.removeNops()`.

https://github.com/googleprojectzero/fuzzilli/blob/872e46814409399dbfacd885495c49f673e54780/Sources/Fuzzilli/Minimization/Minimizer.swift#L74-L103

Assuming this behaviour is _not_ intended and you have some clues of why it is happening, feel free to point me into the correct direction and I am happy to work on a PR.

**Comment by carl-smith** [comment]
Hey Tobias, 

thanks for letting us know, this is definitely not intended.
Like you already mentioned, it seems that we have Nops in our code that have the .notRemovable flag, which is not desired.
This can only happen if we actually create this MinimizationHelper with code that *already has* a Nop. We leak Nops into programs here: https://github.com/googleprojectzero/fuzzilli/blob/fb797471242e5f9abceebd698273730f596ebe47/Sources/Fuzzilli/Minimization/MinimizationPostProcessor.swift#L104
Specifically, in the code above we insert Nops and commit that code but we might fail to remove those Nops we added for padding.

This is now fixed with: https://github.com/googleprojectzero/fuzzilli/commit/d9b7550dffb436bd72ca136a94314b15cd4ce106

Thanks for offering your help with this but since this was such a simple fix I just went ahead and fixed it!
