### ISSUE TITLE
black list for specific function

### ISSUE THREAD

**Issue by zhouat** [googleprojectzero/fuzzilli#47]
Hello,

How to add black list for specific function?

**Comment by saelo** [comment]
You can modify Fuzzilli's environment model and remove functions, objects, methods, etc. from it by changing [JavaScriptEnvironment.swift](https://github.com/googleprojectzero/fuzzilli/blob/master/Sources/Fuzzilli/Core/JavaScriptEnvironment.swift). For example, if you comment out this line: https://github.com/googleprojectzero/fuzzilli/blob/8b2e6a110f9cddaab21946789642fef369e41e71/Sources/Fuzzilli/Core/JavaScriptEnvironment.swift#L138 Fuzzilli will no longer generate code like `eval(...)`. However, Fuzzilli can still end up calling `eval`, for example by enumerating the properties of the global `this` object (of which `eval` is a property). If you need to avoid that as well you probably have to patch the engine to remove the function altogether.

**Comment by zhouat** [comment]
hello saelo,
thanks for your help.
