### ISSUE TITLE
How to run it over a cluster of VMs?

### ISSUE THREAD

**Issue by imanoracle** [googleprojectzero/fuzzilli#51]
Thank you for this great project. Is there any way to use it on scale? `(--networkMaster=host:port)`
and how slaves collaborate with master to avoid redundant work? Also, it does not use all the cores in the system, is there any specific switch to do that?

**Comment by saelo** [comment]
Hey! Yes, use the networkMaster and networkWorker flags for that. I usually have one central master instance (--networkMaster), N intermediate master (--networkMaster + --networkWorker) and roughly N*16 workers (--networkWorker) connected to the intermediate masters. For now, you have to use network synchronization locally as well, so with 16 cores just run one master and 15 workers for example.

**Comment by imanoracle** [comment]
Thank you!

**Comment by ty5491003** [comment]
@imanoracle Hello bro, I have some questions but I can't contact the author now, so i want to ask you for help! My questions as follows:

1. I read `readme.md` of this repo and I noticed that the word "corpus" was mentioned several times. According to the description, as if the corpus is the start point of all work, but i can't find the corpus in anywhere.  So I want to know that Is the corpus existing or generated at run time?

2. What's mean of 'interesting sample'? 

Looking for your reply and thank you in advance.

**Comment by imanoracle** [comment]
Hi there,
Corpus is generated in memory, unless you force it to generate it on disk
by using one of those switches (I forgot right now).

Best,
Iman

**Comment by ty5491003** [comment]
@imanoracle Firstly, thanks for your reply. And 

> unless you force it to generate it on disk by using one of those switches (I forgot right now).

Does "those switch" is refer to `--storagePath`  ?

**Comment by saelo** [comment]
https://github.com/googleprojectzero/fuzzilli/commit/5dca6712dacfeae7f7caef8d981e734a6b19e11d should also help when running fuzzilli at scale. Closing this issue now :)
