### ISSUE TITLE
Fuzzilli options to generate js from grammar file and linter

### ISSUE THREAD

**Issue by TheCrott** [googleprojectzero/fuzzilli#61]
I'm learning fuzzilli now, but I don't know my grammar correct or not. I think by adding options to generate js given grammar file, we can check resulting js valid or not.

`fuzzilli generate example_grammar`
generate js from `example_grammar`

`fuzzilli generate -n 5 example_grammar`
generate 5 js combinations from `example_grammar`

Adding linter I think will be helpful too
`fuzzilli lint example_grammar`
a linter to check correctness of a grammar

**Comment by saelo** [comment]
Fuzzilli is not a grammar-based fuzzer, instead it is based on mutations on a custom IL: https://github.com/googleprojectzero/fuzzilli#concept

For a grammar-based fuzzer, take a look at domato for example: https://github.com/googleprojectzero/domato :)
