### ISSUE TITLE
webkit.patch out of date

### ISSUE THREAD

**Issue by zzywysm** [googleprojectzero/fuzzilli#63]
The webkit.patch in the JavaScriptCore profile no longer applies cleanly because of the change made in https://github.com/WebKit/webkit/commit/022e9c2de70d83020825e8596b26a105b00b8b9d

Please update the diff so that hunk 10 no longer fails.

**Comment by drtychai** [comment]
#66 resolves this issue; patch applies cleanly to Webkit/webkit@dd7f161.

**Comment by saelo** [comment]
Thanks @drtychai for the PR!
