### ISSUE TITLE
Fairly high failure rate when trying to import state

### ISSUE THREAD

**Issue by nclman** [googleprojectzero/fuzzilli#70]
I have not tested this extensively, but quite often, when I try to resume a fuzzing state by using importState, I get an error like: 

[Cli] Failed to import state: The operation could not be completed. (SwiftError error 0.)

My state file can be fairly large (a few megabytes). Not sure what the problem could be.
Suspecting it could be something to do with JSONDecoder? Will update if I find anything.

**Comment by saelo** [comment]
Hi! Interesting, thanks for reporting. I haven't run into this issue, but tbf I rarely use the stateImport feature myself. Maybe you can try adding some print statements around here: https://github.com/googleprojectzero/fuzzilli/blob/3459f6544ccb86e5a9f3b16576e3191318aa7e85/Sources/FuzzilliCli/main.swift#L225 to see whether the file is read successfully and the JSON decoding fails. Is this on Linux or macOS? Could it maybe be an out-of-memory issue during decoding?

**Comment by nclman** [comment]
We can close this issue. The problem was caused by my code.

But I still think the probability of "state.json" file getting too large or corrupted should be addressed.
Perhaps it can be split into separate corpus program JSONs for easier debugging/management.
