### ISSUE TITLE
Failed to communicate with child process with v8

### ISSUE THREAD

**Issue by hhroot** [googleprojectzero/fuzzilli#78]
test@test:~/fuzzilli/Targets/V8/v8$ swift run -c release FuzzilliCli --profile=v8 --storagePath=./out/storagePath ./out/fuzzbuild/d8 
[REPRL] Failed to communicate with child process
[REPRL] Failed to communicate with child process

**Comment by saelo** [comment]
You can use [this tool](https://github.com/googleprojectzero/fuzzilli/blob/master/Misc/REPRL/tester.c) to debug the REPRL. Just compile it and point it to the binary, then press 'r', it should then run that bit of JS code.

You are using v8 at commit ffa14bc12c71f817f31eaeaa7dbe4c90871f67d6 and the patches apply cleanly?

**Comment by hhroot** [comment]
> 您可以使用[此工具](https://github.com/googleprojectzero/fuzzilli/blob/master/Misc/REPRL/tester.c)调试REPRL。只需将其编译并指向二进制文件，然后按“ r”，然后它将运行该段JS代码。

Let me try

**Comment by hhroot** [comment]
let me try

**Comment by saelo** [comment]
Closing this, feel free to reopen or create a new issue if this persists
