### ISSUE TITLE
Improve loops in FuzzIL

### ISSUE THREAD

**Issue by saelo** [googleprojectzero/fuzzilli#8]
FuzzIL's representation of loops is oversimplified and cannot express the fact that more or less arbitrary computations can be performed in the loop header. This might, however, be interesting for things like JIT compiler fuzzing. As such it might make sense to split loops into constructs such as:

```
BeginLoopHeader
...
BeginLoopBody
...
EndLoop
```

However, the loop header has special requirements as only expressions are valid in there but not additional statements (so e.g. you cannot put more control flow operations into it). This would have to be expressed somehow (e.g. as a new [context](https://github.com/googleprojectzero/fuzzilli/blob/f6edda203f1c6bc3b38af49812f75b8f7102f9f7/Sources/Fuzzilli/FuzzIL/Analyzer.swift#L191)).

Additionally, it might make sense to define something like a "loop variable", which could be something as simple as a Phi that is emitted by the LoopHead. This would simplify the current code generators for loops.

**Comment by saelo** [comment]
Basically, JITing is just based on a simple counter: every unit of code (function or possibly loop body) has a counter counting how often it has been executed. Once the counter reaches a certain value, the code is JIT compiled. JSC and Spidermonkey work that way afaik. V8 does it slightly differently: there the JS execution stack is regularly inspected and the counter of every function on the stack is incremented (this approach probably favours long-running functions). In both cases, it's basically enough to just execute the function multiple times. This is easiest achieved through some form of loop, but the concrete form of that loop (a for loop, a while loop, etc.) shouldn't matter.

That said, it might still be interesting to have a `JITCall` instruction which behaves like a function call but executes the given function a specific number of time to force compilation. It's not clear if that would be superior to the [current approach](https://github.com/googleprojectzero/fuzzilli/blob/master/Sources/FuzzilliCli/Profiles/V8Profile.swift#L17) but could be something to experiment with.

**Comment by oicu0619** [comment]
Do you have any further thought about the problem? it is not easy to compile JS with expressions in loop header to Fuzzil OP. Thanks!

**Comment by saelo** [comment]
So once https://github.com/googleprojectzero/fuzzilli/pull/256 lands, we should be able to properly implement loops, in particular loop headers.

For that, we first need to split what is currently the `.script` context into two new contexts, e.g. `.statement` and `.expression`, and use the two everywhere where we currently use `.script`.

Then, the general approach would be to split loops into three operations: `BeginXLoopHeader`, `BeginXLoopBody`, `EndXLoop`. The `BeginXLoopHeader` would open `[.expression]` context _but not_ `.statement`. As such, everything that is an expression is allowed inside the header, but nothing else. The `BeginXLoopBody` would then open `[.loop, .statement, .expression]` context, and so statements etc. are allowed in the body.

Then, we'd probably just use the output of the last instruction in the loop header as loop condition (this basically happens automatically if we lift them as `while (expr1, expr2, expr3) { ... }`. (Note, there are some operations, e.g. `StoreProperty`, that don't have outputs in FuzzIL, but would still work here, e.g. `while (a[42] = 1337) { ... }`. Not sure if we want to allow that.)

One issue is that we can't define new variables inside the loop header. So if we don't find a good way to work around that, we might need to do something like that, which is probably not great...

```javascript
let i = ...;
...
let loopV7, loopV8;
while (loopV7 = foo(), loopV8 = i++, i < loopV7) {
    ...;
}
```

Any thoughts welcome!

**Comment by saelo** [comment]
This is now fixed with https://github.com/googleprojectzero/fuzzilli/commit/dd75a782b14d111a37021faf10f5a3448d63a7e6 and https://github.com/googleprojectzero/fuzzilli/commit/c76ea0edfb5a59e0e762a2c1a01351f4604b3935
