### ISSUE TITLE
Error in V8.patch

### ISSUE THREAD

**Issue by hotwinter** [googleprojectzero/fuzzilli#9]
When applying the given v8 patch, it would result in the following error
```
../../src/d8.cc:2502:9: error: use of undeclared identifier 'success'
        success = false;
```
I think this line should be changed to

```exception_was_thrown = true;```

instead? Without this line, the Fuzzer would fail with
```
[Fuzzer] Cannot detect failed executions (exit code must be nonzero when an uncaught exception was thrown)
```

**Comment by saelo** [comment]
Ah hm, what v8 version is that? In the one that I'm using (1ca088652d3aad04caceb648bcffef100bc4abc0) the variable seems to be called `success`: https://github.com/v8/v8/blob/1ca088652d3aad04caceb648bcffef100bc4abc0/src/d8.cc#L2968

**Comment by hotwinter** [comment]
Ah...my bad, I used the one in the latest release, which I believe is 51df567dd66bdea870c9a93f445ee50b7bbd6735
