### ISSUE TITLE
v8 patch removed

### ISSUE THREAD

**Issue by bzyo** [googleprojectzero/fuzzilli#90]
v8 patch was removed with latest revision update on commit [c1dad0a](https://github.com/googleprojectzero/fuzzilli/commit/c1dad0a7a144faa002b4364676ae1e830b12b853). should this be?

**Comment by saelo** [comment]
Yes, the Fuzzilli patches are now part of upstream v8: https://github.com/v8/v8/commit/70eb08982c68485643f37090d1396a445fb5eed0

**Comment by saelo** [comment]
Ah yeah, but removing the Patches/ directory entirely was in fact not correct: https://github.com/googleprojectzero/fuzzilli/commit/b4d7e7a89bebcf998879d67b9c8d2ea2882d6ce7 :)
